/** All numeric illustration assumptions belong to a fictional example, not a client result. */
export const CASH_BURN_GUIDE_HTML = `<p><strong>Le cash burn décrit la consommation de trésorerie sur une période. Le runway estime combien de temps le cash disponible couvrirait un burn net positif supposé constant.</strong> Ce ratio est un indicateur, pas une date certaine de rupture ni une promesse de financement.</p>
<p>Un <a href="/daf-externalise">DAF externalisé</a> peut rapprocher les données et construire les scénarios avec votre équipe. Pour distinguer les encaissements, les investissements et le financement, commencez par les <a href="/ressources/blog/flux-de-tresorerie">flux de trésorerie</a>.</p>
<h2 id="methode">Calculer son burn rate : définir les flux retenus</h2>
<p>Définition de travail à documenter : le burn brut correspond aux dépenses payées sur la période ; le burn net soustrait les encaissements d’activité retenus. Les investissements, dettes et financements doivent rester identifiables pour ne pas confondre consommation d’exploitation et variation du solde bancaire.</p>
<pre><code>Burn net de la période = dépenses payées retenues − encaissements d’activité retenus</code></pre>
<ul><li>Précisez les comptes, la période et les catégories retenues.</li><li>Utilisez les paiements et recettes réellement intervenus, sans assimiler MRR, factures ou revenu comptable au cash encaissé.</li><li>Distinguez les flux exceptionnels et saisonniers : un mois isolé ne résume pas nécessairement la consommation future.</li><li>Rapprochez le résultat des variations bancaires en expliquant les investissements et financements exclus du calcul.</li></ul>
<h2 id="exemple">Exemple pédagogique fictif : un mois d’activité</h2>
<p>Ces montants sont des hypothèses inventées pour expliquer le calcul. Ils ne décrivent ni une mission Iter ni un niveau de dépenses ou de charges sociales standard.</p>
<table><caption>Hypothèses de paiements et encaissements du mois fictif</caption><thead><tr><th scope="col">Poste</th><th scope="col">Montant</th></tr></thead><tbody>
<tr><th scope="row">Salaires et charges payés</th><td>97 875 €</td></tr><tr><th scope="row">Loyer et charges</th><td>4 500 €</td></tr><tr><th scope="row">Outils et logiciels</th><td>3 200 €</td></tr><tr><th scope="row">Marketing</th><td>12 000 €</td></tr><tr><th scope="row">Services externes</th><td>5 800 €</td></tr><tr><th scope="row">Frais généraux</th><td>2 500 €</td></tr><tr><th scope="row">Total des dépenses payées retenues</th><td>125 875 €</td></tr><tr><th scope="row">Encaissements d’activité retenus</th><td>45 000 €</td></tr><tr><th scope="row">Burn net</th><td>80 875 €</td></tr></tbody></table>
<p>Calcul : 125 875 − 45 000 = 80 875 € consommés sur le mois. Les investissements et nouveaux financements sont supposés absents dans cet exemple ; sinon, ils devraient être traités séparément.</p>
<h2 id="runway">Calculer son runway et en connaître les limites</h2>
<pre><code>Runway estimé en mois = trésorerie disponible / burn net mensuel positif</code></pre>
<p>Avec 650 000 € disponibles et un burn supposé constant de 80 875 € par mois, le ratio est d’environ 8,04 mois. Ce prolongement de l’exemple fictif suppose l’absence de nouveau financement, d’investissement exceptionnel et de changement du rythme des flux.</p>
<p>Si le burn net est nul ou négatif, cette formule ne fournit pas un horizon d’épuisement pertinent. Une trésorerie contractuellement indisponible ne doit pas être confondue avec du cash utilisable. Même avec un runway positif, une échéance concentrée peut créer une tension avant l’horizon moyen.</p>
<h2 id="seuils">Lire l’horizon selon votre contexte</h2>
<p>Il n’existe pas ici de seuil universel obligeant à lever à neuf, douze ou dix-huit mois. Examinez le calendrier des dépenses engagées, la saisonnalité, la fiabilité des ventes attendues et le délai propre aux démarches de financement envisagées.</p>
<table><caption>Questions à examiner plutôt qu’un classement automatique en zones</caption><thead><tr><th scope="col">Situation</th><th scope="col">Question à traiter</th></tr></thead><tbody><tr><th scope="row">Encaissements incertains</th><td>Quel solde reste disponible si le client paie plus tard ?</td></tr><tr><th scope="row">Recrutements ou investissement</th><td>Quelles dépenses sont déjà engagées et quelles options restent réversibles ?</td></tr><tr><th scope="row">Financement en discussion</th><td>Quel scénario reste viable si le financement n’arrive pas à la date envisagée ?</td></tr></tbody></table>
<h2 id="regle-or">Préparer le financement sans le compter comme acquis</h2>
<p>Le plan distingue les fonds disponibles, les financements confirmés et les démarches encore en discussion. La date, le montant et les conditions d’une levée ne sont pas garantis. Le runway ne permet pas de déduire mécaniquement une décote de valorisation.</p>
<h2 id="forecast">Anticiper avec un forecast</h2>
<p>Reliez les recrutements, les charges, les investissements et les hypothèses de revenus au calendrier de cash. Comparez un scénario central à des variantes pertinentes pour votre activité : recettes retardées, croissance plus faible ou lancement d’un projet différé.</p>
<p>Le <a href="/services/previsionnel-tresorerie">prévisionnel de trésorerie à 13 semaines</a> permet d’examiner les dates des échéances proches. Le <a href="/fractional-cfo-startups">Fractional CFO pour startups et SaaS</a> relie les scénarios au budget et au reporting investisseurs. Pour une activité de R&amp;D longue, le <a href="/daf-externalise/deep-tech">pilotage financier deep tech</a> distingue les jalons et les aides confirmées des financements sollicités.</p>
<h2 id="reduire-burn">Examiner les options et leurs effets</h2>
<p>Un gel de recrutement, une modification des dépenses commerciales ou une renégociation ne produit pas le même effet dans toutes les entreprises. Vérifiez les engagements contractuels, les délais de mise en œuvre et les conséquences sur l’activité avant de modifier le plan.</p>
<ul><li>Documenter les dépenses engagées et les économies encore possibles.</li><li>Relier les décisions commerciales aux marges et aux encaissements.</li><li>Suivre les écarts au réalisé et attribuer la mise à jour des hypothèses.</li><li>Examiner les coûts et conditions des options de financement avec les conseils concernés.</li></ul>
<p>Pour le cadre de présentation des mouvements de trésorerie, la <a href="https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/">présentation officielle d’IAS 7 par l’IFRS Foundation</a> distingue exploitation, investissement et financement. Elle ne définit pas un seuil de runway ni une règle de levée applicable à toutes les startups. Source consultée le 2 octobre 2026 ; ce guide est pédagogique et ne remplace pas une analyse de votre situation.</p>
<p><a href="/contact#tresorerie">Présenter mes échéances et mes données de trésorerie</a>.</p>`;
