import type { Locale } from "@/lib/i18n";
import { getDafSubContent, type DafSubContent } from "./daf-sub";
import { getDafOffer } from "./daf-offer";
import { FORMULES } from "./facts";
import { parityHref } from "@/lib/locale-route-map";

const role = {
 en: {
  meta: { title: "CFO: definition, responsibilities and role | Iter Advisors", description: "What does a CFO do? Explore finance leadership responsibilities, skills, working arrangements and the distinction from the external accountant." },
  parentLabel: "Fractional CFO", breadcrumbLabel: "The CFO role", h1: "CFO: definition, role and responsibilities of the finance director", ctaButton: "Discuss my needs",
  headings: [undefined, "The CFO's main responsibilities", "Skills and career paths", "In-house, part-time or interim CFO: how does it work?", "Salary, fees and budget: compare like for like", "Working in this role at Iter", "FAQ: the CFO role", "Working as a CFO at Iter Advisors"],
  paragraphs: [
   ["**The CFO, or Chief Financial Officer, leads a company's finance function: cash flow, budgeting, reporting, financing and accounting coordination.** The CFO helps management understand results, anticipate needs and prepare decisions. The scope depends on the company's size and organisation.", "The French title DAF (directeur administratif et financier), finance director and CFO refer to related roles. DAF emphasises administrative responsibilities, which may include payroll or HR coordination. These responsibilities must be agreed with the relevant teams and advisers. To delegate this work to a [Fractional CFO](/daf-externalise), see our service overview."],
   ["**Cash flow and working capital:** monitor receipts, payments and commitments; build forecasts, document assumptions and prepare banking discussions. [Working capital requirements](/ressources/glossaire/besoin-fonds-roulement-bfr) help explain the gap between trading activity and cash flow.", "**Budgeting and financial strategy:** develop revenue, cost, investment and recruitment scenarios. The CFO highlights trade-offs; management retains the decisions that fall within its authority.", "**Reporting and management accounting:** reconcile data, track results and explain budget variances. [Management accounting](/services/controle-de-gestion-externalise) supports margin analysis by activity, product or channel.", "**Accounting and closing:** organise data collection, the calendar and account reviews with the accounting team, external accountant and, where applicable, statutory auditor. Each party's responsibilities remain defined by their respective mandates.", "**Financing and transactions:** prepare a financial model, data room and discussions with investors or lenders. Depending on the mandate, the CFO contributes to the financial work for acquisitions, disposals and integration.", "**Administration and risks:** coordinate deadlines, controls and access to tools. In some SMEs the CFO also monitors administrative or HR matters with the relevant professionals, without replacing their expertise."],
   ["The role combines accounting and finance skills, data analysis, business understanding and the ability to explain choices to management. The CFO must work with operational teams, banks and external advisers.", "Career paths may include audit, management accounting, accounting or finance leadership. Experience and knowledge of tools must fit the context: an SME, startup, subsidiary or multi-entity group. There is no single career path suited to every engagement.", "Automation can support data collection and reporting preparation. Data controls, confidentiality and human validation remain necessary. Our [AI and finance resources](/ressources/ia-finance) explain applications and their limitations."],
   ["**In-house:** the CFO is employed within the company. This model may suit a sustained need for daily presence and management of the finance function.", "**Part-time:** the professional supports several companies on a recurring basis, with agreed scope and availability. Explore our [Fractional CFO service](/daf-externalise) for responsibilities, contacts and documented cases, then [part-time working arrangements](/daf-externalise/temps-partage) for ongoing coordination.", "**Interim:** the CFO takes on a temporary replacement or transformation mandate and organises the handover. Our [interim CFO service](/daf-externalise/transition) explains the relevant situations and responsibilities to agree."],
   ["A CFO's gross salary, total employer cost and a firm's fees are three different amounts. Compare scope, seniority, availability, employment costs and any additional expenses before comparing budgets.", "[Iter's pricing](/daf-externalise/tarifs) sets out the firm's retainers; it is not a salary survey or study of market prices. The [Fractional versus in-house CFO comparison](/ressources/blog/daf-externalise-vs-daf-salarie) explains the decision criteria.", "Return on investment cannot be promised from the first month. Results are measured over an agreed period: reporting quality, cash visibility, verified savings and decisions supported."],
   ["For the profiles sought and application process, see [becoming a Fractional CFO at Iter Advisors](/carrieres/fractional-cfo). Recruitment terms are separate from client pricing."],
   ["**What does DAF mean?** DAF is the French abbreviation for directeur administratif et financier: administrative and finance director. The role coordinates financial management and, depending on the organisation, some administrative functions.", "**What is the difference between a DAF and a CFO?** CFO means Chief Financial Officer. The titles describe related roles; the actual responsibilities matter more than the job title.", "**How does a CFO differ from an external accountant?** The CFO organises financial management and prepares decisions with management. The accountant performs the work set out in the engagement letter. The roles complement each other and responsibilities must be clearly allocated. See our [CFO and accountant comparison](/ressources/blog/daf-externalise-vs-expert-comptable).", "**Must a CFO be a chartered accountant?** The French expertise comptable qualification is not a general prerequisite for a DAF role in France. This description does not establish professional requirements in another country. Required skills and qualifications depend on the work entrusted; regulated activities remain with authorised professionals.", "**Can an SME have a CFO without a full-time hire?** Yes, a [Fractional CFO](/daf-externalise) can work within an agreed scope. Needs, internally handled work and expected availability determine the appropriate arrangement."],
   ["Interested in this profession? Our [Fractional CFO careers page](/carrieres/fractional-cfo) describes the working framework. [Current vacancies](/jobs) explain the profiles sought and how to apply. This recruitment journey is distinct from the CFO service for businesses."],
  ],
 },
 es: {
  meta: { title: "CFO: definición y funciones | Iter Advisors", description: "¿Qué hace un director financiero? Sus funciones, competencias, modalidades de trabajo y diferencias con la asesoría contable." },
  parentLabel: "CFO externo", breadcrumbLabel: "Funciones del CFO", h1: "CFO: definición, papel y funciones del director financiero", ctaButton: "Hablar de mi necesidad",
  headings: [undefined, "Las principales funciones del CFO", "Competencias y trayectoria profesional", "CFO interno, a tiempo parcial o de transición: ¿cómo funciona?", "Salario, honorarios y presupuesto: comparar conceptos equivalentes", "Ejercer esta función en Iter", "FAQ: las funciones del CFO", "Trabajar como CFO en Iter Advisors"],
  paragraphs: [
   ["**El CFO, o director financiero, dirige la función financiera de una empresa: tesorería, presupuesto, reporting, financiación y coordinación contable.** Ayuda a la dirección a entender los resultados, anticipar necesidades y preparar decisiones. Su alcance depende del tamaño y de la organización de la empresa.", "DAF (directeur administratif et financier en francés), director financiero y CFO designan funciones próximas. DAF subraya la dimensión administrativa, que puede incluir la coordinación de nóminas o asuntos de RR. HH. Estas responsabilidades deben acordarse con los equipos y asesores competentes. Para confiar esta gestión a un [CFO externo](/daf-externalise), consulte nuestro acompañamiento."],
   ["**Tesorería y capital circulante:** seguir cobros, pagos y compromisos; elaborar previsiones, explicitar hipótesis y preparar conversaciones con bancos. Las [necesidades de capital circulante](/ressources/glossaire/besoin-fonds-roulement-bfr) ayudan a entender el desfase entre actividad y tesorería.", "**Presupuesto y estrategia financiera:** elaborar escenarios de ingresos, gastos, inversiones y contrataciones. El CFO pone de manifiesto las alternativas; la dirección conserva las decisiones que le corresponden.", "**Reporting y control de gestión:** conciliar datos, seguir resultados y explicar desviaciones presupuestarias. El [control de gestión](/services/controle-de-gestion-externalise) permite analizar márgenes por actividad, producto o canal.", "**Contabilidad y cierre:** organizar la recopilación de datos, el calendario y la revisión de cuentas con el equipo contable, la asesoría y, cuando corresponda, el auditor. Las responsabilidades de cada parte siguen definidas por sus respectivos mandatos.", "**Financiación y operaciones:** preparar un modelo financiero, una data room y las conversaciones con inversores o prestamistas. Según el mandato, el CFO participa en los trabajos financieros de adquisiciones, ventas e integración.", "**Administración y riesgos:** coordinar vencimientos, controles y accesos a herramientas. En algunas pymes también sigue asuntos administrativos o de RR. HH. con los profesionales pertinentes, sin sustituir sus competencias."],
   ["La función combina conocimientos contables y financieros, análisis de datos, comprensión de la actividad y capacidad para explicar opciones a la dirección. El CFO debe trabajar con equipos operativos, bancos y asesores externos.", "Las trayectorias pueden pasar por auditoría, control de gestión, contabilidad o dirección financiera. La experiencia y el conocimiento de herramientas deben ajustarse al contexto: pyme, startup, filial o grupo con varias entidades. No existe una única trayectoria adecuada para todas las misiones.", "La automatización puede facilitar la recopilación de datos y la preparación del reporting. El control de datos, la confidencialidad y la validación humana siguen siendo necesarios. Nuestros [recursos de IA y finanzas](/ressources/ia-finance) detallan usos y límites."],
   ["**Interno:** el CFO forma parte de la plantilla. Puede ser adecuado cuando se necesita presencia diaria y gestión permanente de la función financiera.", "**A tiempo parcial:** el profesional interviene de manera recurrente en varias empresas, con alcance y disponibilidad acordados. Consulte la oferta de [CFO externo](/daf-externalise) para funciones, interlocutores y casos documentados, y el [funcionamiento a tiempo parcial](/daf-externalise/temps-partage) para organizar el seguimiento.", "**De transición:** el CFO asume un mandato temporal de sustitución o transformación y organiza el traspaso. La [misión de CFO de transición](/daf-externalise/transition) precisa las situaciones y responsabilidades que deben definirse."],
   ["El salario bruto de un CFO, su coste para la empresa y los honorarios de una firma son importes distintos. Compare alcance, experiencia, disponibilidad, cargas y gastos adicionales antes de comparar presupuestos.", "La [tabla de precios de Iter](/daf-externalise/tarifs) presenta las cuotas de la firma; no constituye un estudio de salarios ni de precios de mercado. La [comparativa entre CFO externo e interno](/ressources/blog/daf-externalise-vs-daf-salarie) explica los criterios de elección.", "No se promete rentabilidad desde el primer mes. Los resultados se miden durante un periodo definido: calidad del reporting, visibilidad de tesorería, ahorros constatados y decisiones facilitadas."],
   ["Para conocer los perfiles buscados y el proceso de candidatura, consulte [trabajar como Fractional CFO en Iter Advisors](/carrieres/fractional-cfo). Las condiciones de contratación laboral son distintas del precio facturado al cliente."],
   ["**¿Qué significa DAF?** DAF es la abreviatura francesa de directeur administratif et financier, director administrativo y financiero. Coordina la gestión financiera y, según la organización, parte de las funciones administrativas.", "**¿Qué diferencia hay entre DAF y CFO?** CFO significa Chief Financial Officer. Ambos títulos abarcan funciones próximas; el alcance real del puesto importa más que su nombre.", "**¿Qué diferencia hay entre el CFO y la asesoría contable?** El CFO organiza la gestión financiera y prepara decisiones con la dirección. La asesoría realiza los trabajos previstos en su contrato. Sus intervenciones son complementarias y sus responsabilidades deben distribuirse claramente. Consulte la [comparativa entre CFO y asesoría contable](/ressources/blog/daf-externalise-vs-expert-comptable).", "**¿Debe un CFO ser experto contable?** La titulación francesa de expertise comptable no es un requisito general para ejercer como DAF en Francia. Las competencias y cualificaciones dependen del trabajo encargado; las actividades reservadas corresponden a profesionales habilitados. Traducir esta descripción no la convierte en una regla profesional española.", "**¿Puede una pyme tener CFO sin contratar a tiempo completo?** Sí, un [CFO externo](/daf-externalise) puede intervenir con un alcance acordado. Las necesidades, los trabajos internos y la disponibilidad esperada permiten elegir la organización adecuada."],
   ["¿Quiere ejercer esta profesión? La página de [carrera de Fractional CFO](/carrieres/fractional-cfo) presenta el marco de trabajo. Las [ofertas abiertas](/jobs) detallan perfiles y candidaturas. Este recorrido de selección es distinto de la oferta de CFO dirigida a empresas."],
  ],
 },
};

const pricing = {
 en: {
  title: "Fractional CFO pricing: packages and budget", metaTitle: "Fractional CFO pricing 2026: fees by engagement", parent: "Fractional CFO", breadcrumb: "Pricing", cta: "Request a quote",
  headings: [undefined, "2026 pricing table", "Three examples to prepare your budget", "What is included and what needs a separate quote", "What our clients actually pay", "What affects the price?", "Comparing alternatives", "How does billing work?", "How do I get a quote?", "Our other CFO pages", "FAQ: Fractional CFO fees"],
  intro: (price: string) => [`Choose a finance leadership scope with a monthly retainer and deliverables defined in the quote. Recurring packages range from **${price}**, depending on the profile and complexity.`, "Below are the official pricing table, budget examples and scoping criteria. For billing models and alternatives, see our **[guide to Fractional CFO costs](/ressources/blog/cout-daf-externalise-tarifs-prix-2026)**."],
  grid: ["Three monthly packages: prices exclude VAT; days are indicative averages", "Package", "Monthly fee excl. VAT", "Indicative days", "Included deliverables", "Profile"],
  outputs: ["Monthly P&L, cash and KPI reporting; 13-week cash forecast; monthly finance review with management; ad hoc support.", "Essential scope, plus a 3–5-year business plan, fundraising, non-dilutive debt, post-funding structuring and investor reporting.", "Growth scope, plus M&A and due diligence, board and governance, international expansion, finance data and BI."],
  profiles: ["Dedicated senior CFO or Finance Manager, with peer review by a partner.", "Dedicated senior CFO.", "Dedicated senior CFO and financial analyst."],
  gridText: ["The packages above cover recurring support. Interim and one-off assignments are priced separately.", "Interim CFO: intensive support for a replacement, crisis or transformation. Indicative fee: EUR 8,000–12,000 excl. VAT/month, quoted separately. Duration and handover are agreed during scoping.", "One-off assignment: financial preparation for fundraising, seller assistance, buyer due diligence or a finance function review. Each receives a specific quote based on entities, data, deliverables and schedule. These services are not assumed to be part of a recurring retainer."],
  examples: ["Simulated budgets excluding VAT and any additional expenses: the quote confirms scope", "Example need", "Monthly reference", "Three-month budget", "Check during scoping"],
  needs: ["SME: organise reporting and cash monitoring", "Growing business: strengthen budgeting and reporting", "Multi-entity group: coordinate finance leadership"],
  checks: ["Account quality, indicators and contacts", "Entities, forecasts and review frequency", "Consolidation complexity, governance and projects"],
  exampleText: "These examples apply package ranges to three months. They are simulations, not client engagements or a minimum commitment period. The need alone does not automatically determine the package: profile and scope are assessed together.",
  inclusion: ["**Included in the retainer:** deliverables and discussions within the agreed scope. The quote details reporting, forecasts, meetings, contacts and expected availability.", "**Specify separately:** software licences, external accountant or adviser fees, travel and any out-of-scope transaction. Fundraising, due diligence or a major migration should not be assumed included unless stated in the quote.", "**Changing needs:** additional scope requires a signed amendment. Days are indicative; the commitment covers the scope of work.", "**[Request a quote for my scope](/contact)**: share the number of entities, tools, main priority and desired start date."],
  portfolio: ["Across our Fractional CFO engagements, **40% of clients use Essential, around EUR 3,000 excl. VAT/month; 40% use Growth, around EUR 5,000 excl. VAT/month; and 20% pay more**, for Premium or an interim assignment. These are rounded references, not the boundaries of individual invoices: recurring packages remain EUR 3,000–8,000 excl. VAT/month depending on scope.", "This distribution was observed in our portfolio on 1 September 2026 and rounded to the nearest ten percentage points. It changes with engagements. It does not replace a quote, but answers a practical question: what do other clients pay?"],
  factors: ["Several factors affect the final cost. Experience: a CFO with five years' experience does not have the same cost as one with twenty. All Iter Advisors partners have more than ten years' experience in corporate finance.", "Complexity: simple accounting with one legal entity requires less time than a multi-country structure with foreign currencies, subsidiaries and consolidation obligations.", "Sector: SaaS, e-commerce and biotech may require specific expertise that can justify higher fees.", "On-site arrangements are agreed during scoping. Any travel expenses are separate from the retainer and specified in the quote."],
  alternatives: (salary: string, annual: string) => ["[Accounting outsourcing fees](/ressources/blog/externalisation-comptable) relate to a separate engagement agreed with the accounting firm.", `Fractional versus in-house CFO: our reference for comparable seniority is EUR ${salary} in annual employer cost, including employment charges. Iter packages represent EUR ${annual} excl. VAT/year for a part-time scope. The right choice depends on actual needs: part-time support and full-time employment do not provide the same availability.`, "Fractional CFO versus external accountant: the accountant prepares accounts and handles tax and social compliance within its mandate. The CFO manages financial performance. The roles are complementary; a structured SME typically needs accounting compliance and finance leadership.", "Fractional CFO versus financial consultant: a consultant handles a defined project and leaves after completion. A Fractional CFO develops an ongoing relationship and knows your history. Recurring needs often suit the latter format."],
  billing: ["The service agreement defines scope, deliverables, contacts and monthly fees. Days give an availability reference; they are not a contractual day-rate package.", "Billing is monthly, payable within 30 days. Discussions within the agreed scope are included. Additional scope requires a signed amendment."],
  quote: ["To get a personalised quote, contact us for an initial 30-minute discussion. Together we assess your needs, current financial situation and appropriate involvement.", "We then prepare a detailed proposal, with scope and a schedule agreed together."],
  related: "For recurring arrangements, see **[part-time CFO](/daf-externalise/temps-partage)**; for a temporary replacement or transformation, **[interim CFO](/daf-externalise/transition)**; for responsibilities, **[the CFO role](/daf-externalise/metier)**; and for sector specifics, **[CFO support by sector](/daf-externalise/secteurs)**. The full offer is on our **[Fractional CFO page](/daf-externalise)**. Interim and project work receive separate quotes.",
  faq: ["**Are the fees tax deductible?** Check with your tax adviser based on the company's situation, applicable rules and supporting documents. This page does not provide a tax assessment.", "**Can the fee be negotiated?** We can adapt the entrusted scope to your budget. Package prices follow the profile engaged and the published pricing table.", "**What do most clients pay?** On 1 September 2026, around 40% used Essential at approximately EUR 3,000 excl. VAT/month, 40% Growth around EUR 5,000, and 20% paid more. These rounded references are not invoice boundaries and do not replace a quote.", "**Is there a minimum engagement period?** No minimum duration; cancellation requires 30 days' notice.", "**Does the fee include travel?** For on-site work, travel and accommodation when needed are charged separately at actual cost, as agreed in the quote. Remote support does not incur travel expenses."],
 },
 es: {
  title: "Precios del CFO externo: planes y presupuesto", metaTitle: "Precios CFO externo 2026: honorarios por misión", parent: "CFO externo", breadcrumb: "Precios", cta: "Solicitar un presupuesto",
  headings: [undefined, "Tabla de precios 2026", "Tres ejemplos para preparar su presupuesto", "Qué se incluye y qué se presupuesta por separado", "Qué pagan realmente nuestros clientes", "¿Qué influye en el precio?", "Comparación con las alternativas", "¿Cómo funciona la facturación?", "¿Cómo obtener un presupuesto?", "Otras páginas de dirección financiera", "FAQ: honorarios del CFO externo"],
  intro: (price: string) => [`Elija un alcance de dirección financiera, con una cuota mensual y entregables definidos en el presupuesto. Los planes recurrentes van de **${price}**, según el perfil y la complejidad.`, "A continuación encontrará la tabla oficial, ejemplos de presupuesto y puntos que deben definirse. Para comparar modalidades de facturación y alternativas, consulte la **[guía del coste de un CFO externo](/ressources/blog/cout-daf-externalise-tarifs-prix-2026)**."],
  grid: ["Tres planes mensuales: precios sin IVA y dedicación media orientativa", "Plan", "Cuota mensual sin IVA", "Dedicación orientativa", "Entregables incluidos", "Perfil"],
  outputs: ["Reporting mensual de resultados, tesorería e indicadores; previsión de tesorería a 13 semanas; revisión financiera mensual con la dirección; apoyo puntual.", "Alcance Esencial, más plan de negocio a 3–5 años, rondas, deuda no dilutiva, estructuración tras la ronda y reporting a inversores.", "Alcance Crecimiento, más M&A y due diligence, consejo y gobierno corporativo, internacionalización, datos y BI financieros."],
  profiles: ["CFO o Finance Manager sénior dedicado, con revisión por un socio.", "CFO sénior dedicado.", "CFO sénior dedicado y analista financiero."],
  gridText: ["Los planes anteriores corresponden al acompañamiento recurrente. Las misiones de transición y los proyectos puntuales se presupuestan por separado.", "CFO de transición: intervención intensiva para una sustitución, crisis o transformación. Precio orientativo: 8.000–12.000 € sin IVA al mes, con presupuesto propio. La duración y el traspaso se acuerdan al definir la misión.", "Misión puntual: preparación financiera de una ronda, asistencia al vendedor, due diligence del comprador o diagnóstico de la función financiera. Cada misión tiene un presupuesto específico según entidades, datos, entregables y calendario. No se presume incluida en una cuota recurrente."],
  examples: ["Simulaciones sin IVA ni gastos adicionales: el presupuesto confirma el alcance", "Ejemplo de necesidad", "Referencia mensual", "Presupuesto de tres meses", "Puntos que deben definirse"],
  needs: ["Pyme: organizar el reporting y el seguimiento de tesorería", "Empresa en crecimiento: reforzar presupuesto y reporting", "Grupo con varias entidades: coordinar la dirección financiera"],
  checks: ["Calidad de cuentas, indicadores e interlocutores", "Entidades, previsiones y frecuencia de revisión", "Complejidad de consolidación, gobierno y proyectos"],
  exampleText: "Estos ejemplos aplican las horquillas de los planes a tres meses. Son simulaciones, no misiones de clientes ni una duración mínima de compromiso. La necesidad por sí sola no determina automáticamente el plan: perfil y alcance se evalúan conjuntamente.",
  inclusion: ["**Incluido en la cuota:** entregables e intercambios del alcance acordado. El presupuesto detalla reporting, previsiones, reuniones, interlocutores y disponibilidad esperada.", "**Por separado:** licencias, honorarios de la asesoría contable u otros asesores, desplazamientos y operaciones fuera del alcance. Una ronda, due diligence o migración importante no se presume incluida sin mención expresa.", "**Evolución de la necesidad:** cualquier ampliación requiere un acuerdo adicional firmado. Los días son orientativos; el compromiso se refiere al alcance del trabajo.", "**[Solicitar un presupuesto para mi necesidad](/contact)**: indique número de entidades, herramientas, prioridad y fecha de inicio deseada."],
  portfolio: ["En nuestras misiones de CFO externo, **el 40 % de los clientes utiliza Esencial, alrededor de 3.000 € sin IVA al mes; el 40 % Crecimiento, alrededor de 5.000 €; y el 20 % paga más**, en Premium o una misión de transición. Son referencias redondeadas, no los límites de facturas individuales: la tabla recurrente sigue siendo de 3.000 a 8.000 € sin IVA al mes según el alcance.", "La distribución se observó en nuestra cartera el 1 de septiembre de 2026 y se redondeó a decenas de puntos porcentuales. Cambia con las misiones. No sustituye un presupuesto, pero responde a una pregunta práctica: ¿cuánto pagan otros clientes?"],
  factors: ["Varios factores influyen en el coste. La experiencia: un CFO con cinco años no tiene el mismo coste que uno con veinte. Todos los socios de Iter Advisors tienen más de diez años de experiencia en finanzas corporativas.", "La complejidad: una contabilidad sencilla con una entidad requiere menos tiempo que una estructura multinacional con divisas, filiales y obligaciones de consolidación.", "El sector: SaaS, e-commerce o biotecnología pueden necesitar especialización que justifique honorarios superiores.", "La presencia se acuerda al definir la misión. Los gastos de desplazamiento son distintos de la cuota y se especifican en el presupuesto."],
  alternatives: (salary: string, annual: string) => ["El [precio de la externalización contable](/ressources/blog/externalisation-comptable) corresponde a una misión distinta, acordada con la asesoría.", `CFO externo frente a interno: nuestra referencia para una experiencia equivalente es de ${salary} € de coste anual para el empleador, incluidas las cargas. Los planes Iter representan ${annual} € sin IVA al año para un alcance a tiempo parcial. No es un estudio salarial del mercado español. La elección depende de la necesidad real: una intervención parcial y un puesto a tiempo completo no ofrecen la misma disponibilidad.`, "CFO externo frente a asesoría contable: la asesoría prepara cuentas y atiende el cumplimiento fiscal y laboral de su mandato. El CFO dirige el rendimiento financiero. Son funciones complementarias; una pyme estructurada suele necesitar ambos tipos de trabajo.", "CFO externo frente a consultor financiero: el consultor interviene en un proyecto definido y termina al finalizarlo. El CFO externo construye una relación continua y conoce el historial. Para necesidades recurrentes, este último formato suele ser adecuado."],
  billing: ["El contrato de servicios define alcance, entregables, interlocutores y cuota mensual. Los días orientan sobre disponibilidad; no constituyen un paquete contractual de jornadas.", "La facturación es mensual, con pago a 30 días. Los intercambios del alcance acordado están incluidos. Cualquier ampliación requiere un acuerdo adicional firmado."],
  quote: ["Para obtener un presupuesto personalizado, contáctenos para una primera conversación de 30 minutos. Evaluaremos sus necesidades, situación financiera y dedicación adecuada.", "Después prepararemos una propuesta detallada, con alcance y calendario acordados conjuntamente."],
  related: "Para el acompañamiento recurrente, consulte **[CFO a tiempo parcial](/daf-externalise/temps-partage)**; para una sustitución o transformación temporal, **[CFO de transición](/daf-externalise/transition)**; para las funciones, **[el papel del CFO](/daf-externalise/metier)**; y para particularidades de la actividad, **[CFO externo por sector](/daf-externalise/secteurs)**. La oferta completa está en **[CFO externo](/daf-externalise)**. Transición y proyectos tienen presupuestos propios.",
  faq: ["**¿Son deducibles los honorarios?** Verifíquelo con su asesor fiscal según la situación de la empresa, las normas aplicables y los justificantes. Esta página no constituye una evaluación fiscal.", "**¿Puede negociarse el precio?** Podemos adaptar el alcance encargado a su presupuesto. Los precios siguen el perfil asignado y la tabla publicada.", "**¿Cuánto pagan la mayoría de los clientes?** El 1 de septiembre de 2026, alrededor del 40 % utilizaba Esencial, unos 3.000 € sin IVA al mes; el 40 % Crecimiento, unos 5.000 €; y el 20 % pagaba más. Son referencias redondeadas, no límites de facturas individuales ni un presupuesto.", "**¿Existe duración mínima?** No hay duración mínima; la cancelación requiere 30 días de preaviso.", "**¿Se incluyen los desplazamientos?** En intervenciones presenciales, transporte y alojamiento cuando proceda se facturan aparte al coste real, según el presupuesto. El trabajo a distancia no genera gastos de desplazamiento."],
 },
};

export function getDafReferenceContent(locale: Locale, slug: "tarifs" | "metier"): DafSubContent {
  const source = getDafSubContent("fr", slug)!;
  if (locale === "fr") return source;
  const modified = { date: "2026-10-02", label: locale === "en" ? "2 October 2026" : "2 de octubre de 2026" };
  if (slug === "metier") {
    const t = role[locale];
    return { ...source, meta: t.meta, parentLabel: t.parentLabel, parentHref: parityHref(source.parentHref, locale), breadcrumbLabel: t.breadcrumbLabel, h1: t.h1, ctaButton: t.ctaButton, modified,
      sections: source.sections.map((section, i) => ({ ...section, heading: t.headings[i], content: t.paragraphs[i] })),
    };
  }
  const t = pricing[locale], offer = getDafOffer(locale);
  const paragraphs = [t.intro(offer.price), [offer.billing, `${t.gridText[0]} ${offer.commitment}`, ...t.gridText.slice(1)], [t.exampleText], t.inclusion, t.portfolio, t.factors, t.alternatives(offer.salary, offer.annualPrice), [t.billing[0], `${t.billing[1]} ${offer.commitment}`], t.quote, [t.related], t.faq];
  const number = (value: number) => value.toLocaleString(locale === "en" ? "en-GB" : "es-ES");
  return { ...source, modified, parentLabel: t.parent, parentHref: parityHref(source.parentHref, locale), breadcrumbLabel: t.breadcrumb, h1: t.title, ctaButton: t.cta,
    meta: { title: t.metaTitle, description: `${offer.price}. ${offer.commitment}` },
    sections: source.sections.map((section, i) => ({ ...section, heading: t.headings[i], content: paragraphs[i],
      ...(i === 1 ? { table: { caption: t.grid[0], headers: t.grid.slice(1), rows: offer.tiers.map((plan, index) => [plan.name, plan.price, plan.volume, t.outputs[index], t.profiles[index]]) } } : {}),
      ...(i === 2 ? { table: { caption: t.examples[0], headers: t.examples.slice(1), rows: FORMULES.map((plan, index) => [t.needs[index], offer.tiers[index].price, `${number(plan.prixMin * 3)}–${number(plan.prixMax * 3)} ${locale === "en" ? "EUR excl. VAT" : "€ sin IVA"}`, t.checks[index]]) } } : {}),
    })),
  };
}
