import { contractContent } from "./contract-copy";
import type { Locale } from "@/lib/i18n";
import { FINANCE_SERVICES, type FinanceService } from "./finance-services";
import en from "./locales/finance-services.en.json";
import es from "./locales/finance-services.es.json";

// JSON arrays are validated against the FR tuple shapes by the parity tests.
const translated = { en, es } as unknown as Record<"en" | "es", Record<string, FinanceService>>;
export function getFinanceServices(locale: Locale): Record<string, FinanceService> { return contractContent(locale === "fr" ? FINANCE_SERVICES : translated[locale], locale); }
export function getFinanceService(key: string, locale: Locale): FinanceService { return getFinanceServices(locale)[key]; }

export const financeInterface = {
 fr: { caseNav: "Cas client", teamNav: "Équipe", cta: "Parlons de votre besoin", deliverables: "Voir les livrables", intro: "Premier échange pour préciser votre situation et la suite.", need: "Votre besoin", outputs: "Les livrables", method: "La méthode", budget: "Le budget", answers: "Les réponses", fit: "Le bon accompagnement", fitHeading: "Vous vous reconnaissez dans ces situations ?", concrete: "Du travail concret", inHand: "Ce que vous avez en main", chosen: "Les livrables sont choisis au cadrage, selon vos priorités et les données disponibles.", decide: "Pour décider", practice: "En pratique", calendar: "Un calendrier pour préparer les décisions", shared: "Une méthode partagée", together: "Comment nous travaillons ensemble", responsibilities: "Les responsabilités", overall: "Découvrir notre direction financière externalisée", position: "Situer ce besoin dans une mission de DAF externalisé", quote: "Un périmètre avant un devis.", prices: "Consulter les tarifs DAF", documented: "Une mission documentée", before: "Avant de vous engager", people: "Parler avec les personnes qui interviennent.", readCase: "Lire le cas et son périmètre", caseIntro: "Le premier échange permet de préciser votre situation. Le cadrage identifie ensuite le profil, les compétences et les modalités de collaboration adaptés à la mission.", team: "Découvrir l’équipe Iter", questions: "Vos questions", next: "Pour préparer la suite", resources: "Les ressources utiles", related: "Un besoin complémentaire ?", start: "Commençons par votre situation", decision: "Quelle décision ou échéance souhaitez-vous préparer ?", contact: "Décrivez votre besoin, votre organisation actuelle et votre calendrier. Nous préciserons ensemble les travaux utiles.", describe: "Décrire mon besoin" },
 en: { caseNav: "Client case", teamNav: "Team", cta: "Discuss your needs", deliverables: "View deliverables", intro: "An initial conversation to understand your situation and next steps.", need: "Your need", outputs: "Deliverables", method: "How we work", budget: "Budget", answers: "Answers", fit: "The right support", fitHeading: "Do these situations sound familiar?", concrete: "Practical work", inHand: "What you receive", chosen: "Deliverables are agreed during scoping, according to your priorities and available data.", decide: "Decisions it supports", practice: "In practice", calendar: "A calendar to prepare decisions", shared: "An agreed method", together: "How we work together", responsibilities: "Responsibilities", overall: "Explore our finance leadership", position: "How this fits within a Fractional CFO engagement", quote: "Define the scope before the quote.", prices: "View CFO pricing", documented: "A documented engagement", before: "Before committing", people: "Talk to the people doing the work.", readCase: "Read the case and its scope", caseIntro: "The initial conversation clarifies your situation. Scoping then identifies the profile, skills and working arrangements appropriate to the engagement.", team: "Meet the Iter team", questions: "Your questions", next: "Prepare the next stage", resources: "Useful resources", related: "A related need?", start: "Start with your situation", decision: "Which decision or deadline are you preparing for?", contact: "Describe your needs, current organization and calendar. We will identify useful work together.", describe: "Describe my needs" },
 es: { caseNav: "Caso de cliente", teamNav: "Equipo", cta: "Hablemos de su necesidad", deliverables: "Ver los entregables", intro: "Una primera conversación para precisar su situación y los siguientes pasos.", need: "Su necesidad", outputs: "Entregables", method: "Cómo trabajamos", budget: "Presupuesto", answers: "Respuestas", fit: "El acompañamiento adecuado", fitHeading: "¿Reconoce estas situaciones?", concrete: "Trabajo concreto", inHand: "Qué recibe", chosen: "Los entregables se acuerdan según sus prioridades y los datos disponibles.", decide: "Para decidir", practice: "En la práctica", calendar: "Un calendario para preparar decisiones", shared: "Un método compartido", together: "Cómo trabajamos juntos", responsibilities: "Responsabilidades", overall: "Conocer nuestra dirección financiera", position: "Situar esta necesidad en una misión de CFO externo", quote: "Definir el alcance antes del presupuesto.", prices: "Consultar precios de CFO", documented: "Una misión documentada", before: "Antes de comprometerse", people: "Hablar con quienes realizan el trabajo.", readCase: "Leer el caso y su alcance", caseIntro: "La primera conversación precisa su situación. Después se identifica el perfil, las competencias y las modalidades adecuadas para la misión.", team: "Conocer al equipo Iter", questions: "Sus preguntas", next: "Preparar la siguiente etapa", resources: "Recursos útiles", related: "¿Una necesidad complementaria?", start: "Empecemos por su situación", decision: "¿Qué decisión o vencimiento desea preparar?", contact: "Describa su necesidad, organización y calendario. Precisaremos juntos el trabajo útil.", describe: "Describir mi necesidad" },
};
