import { IA_SOURCES, type IaSourceKey } from "./ia-finance-references";

export interface IaGuide {
  label: string; title: string; description: string; dek: string;
  published: string; image: string; summary: string[];
  sections: { id: string; title: string; html: string }[];
  faq: { question: string; answer: string }[];
  sources: IaSourceKey[]; related: string[];
}
const hub = "/ressources/ia-finance";
const link = (slug: string, label: string) => `<a href="${hub}/${slug}">${label}</a>`;
const source = (key: IaSourceKey, label: string) => `<a href="${IA_SOURCES[key].url}">${label}</a>`;
const table = (caption: string, heads: string[], rows: string[][]) => `<div class="prose-table-wrapper"><table class="min-w-[32rem]"><caption>${caption}</caption><thead><tr>${heads.map(h => `<th scope="col">${h}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map((cell, i) => i === 0 ? `<th scope="row">${cell}</th>` : `<td>${cell}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
const financeImage = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80";

/** Contenu éditorial statique uniquement : aucun HTML provenant d'un utilisateur. */
export const IA_GUIDES: Record<string, IaGuide> = {
  "automatiser-reporting-financier": {
    label: "Automatiser le reporting financier",
    title: "Automatiser le reporting financier : méthode, contrôles et ROI",
    description: "Automatisez le reporting d’une PME : sources, rapprochements, contrôles, exemple de ROI et cas documenté. Une méthode pilotée par la direction financière.",
    dek: "Automatiser le reporting financier consiste à fiabiliser la collecte, appliquer des règles de calcul reproductibles et préparer les commentaires. Le point de départ est un reporting approuvé auquel comparer le nouveau dispositif, avec un responsable pour chaque écart.",
    published: "2026-09-01", image: financeImage,
    summary: ["Séparez la connexion des données, les calculs et les commentaires assistés par IA.", "Validez les totaux et les exceptions avant de diffuser un tableau de bord.", "Mesurez le temps de contrôle et de maintenance dans le retour sur investissement."],
    sections: [
      { id: "perimetre", title: "Quelles étapes du reporting peut-on automatiser ?", html: `<p>Un export programmé ou une formule ne nécessite pas forcément d’IA. Un modèle de langage devient utile pour expliquer des écarts déjà calculés ou préparer une synthèse. Conservez la comptabilité et le modèle de gestion comme références.</p>${table("Répartition des tâches et des contrôles", ["Étape", "Automatisation possible", "Contrôle du DAF"], [["Collecte", "Exports planifiés, API, chargement des écritures", "Période, entité, nombre de lignes et fraîcheur"], ["Calcul", "Règles de mapping et agrégations dans un tableur ou la BI", "Totaux rapprochés de la balance et formules versionnées"], ["Exceptions", "Signalement des doublons et des lignes sans correspondance", "Revue des rejets et des rapprochements ambigus"], ["Commentaire", "Premier jet à partir d’un tableau d’écarts validé", "Causes confirmées, chiffres et décisions relus"]])}<p>Pour concevoir les indicateurs, utilisez notre <a href="/ressources/blog/tableau-de-bord-financier-startup-12-kpis">guide du tableau de bord financier</a>. Le nombre de graphiques dépend des décisions attendues, pas de la capacité du logiciel.</p>` },
      { id: "methode", title: "Comment passer d’Excel à un reporting connecté ?", html: `<ol><li><strong>Figer la référence :</strong> sélectionnez un mois clôturé, documentez les retraitements et conservez l’export approuvé.</li><li><strong>Définir le dictionnaire :</strong> précisez pour chaque indicateur la formule, les comptes inclus, la devise et le traitement des avoirs.</li><li><strong>Connecter une source :</strong> commencez en lecture seule, surveillez les chargements et traitez les données manquantes.</li><li><strong>Comparer en parallèle :</strong> expliquez chaque différence avec l’ancien reporting avant la bascule.</li><li><strong>Documenter la reprise :</strong> prévoyez un export manuel et un responsable si le connecteur s’arrête.</li></ol><p>Le calendrier et les critères de passage sont détaillés dans la ${link("feuille-de-route-90-jours", "feuille de route à 90 jours")}. Ce délai est un cadre de travail à adapter aux accès et à la qualité des données.</p>` },
      { id: "cas", title: "Quel résultat réel est documenté ?", html: `<p>Dans le ${source("usVenture", "cas U.S. Venture publié par Microsoft en janvier 2025")}, la division U.S. AutoForce utilise Copilot for Finance pour les rapprochements de cartes et de relevés bancaires. Le cas annonce plus de 30 heures économisées par mois pour l’équipe concernée.</p><p>Ce résultat porte sur deux processus d’un grand groupe déjà équipé de Dynamics 365. Il ne mesure pas le gain d’une clôture complète ni celui d’une PME française. Notre ${link("retours-experience", "lecture des cas documentés")} précise ce qui peut être repris dans un pilote.</p>` },
      { id: "cout", title: "Comment calculer le ROI sans oublier les coûts cachés ?", html: `<p><strong>Gain mensuel de capacité = (heures avant − heures après, contrôles compris) × coût horaire chargé.</strong> Déduisez ensuite les licences additionnelles, le connecteur et la maintenance. Les heures libérées sont une capacité disponible ; elles ne deviennent une économie de trésorerie que si une dépense diminue effectivement.</p>${table("Exemple pédagogique fictif, pas un résultat client", ["Hypothèse", "Valeur"], [["Production mensuelle avant / après", "20 h / 8 h, contrôles compris"], ["Valorisation du temps", "12 h × 50 € = 600 € par mois"], ["Licences, connecteur et maintenance", "250 € par mois"], ["Gain net de capacité valorisé", "350 € par mois"], ["Mise en place et amortissement indicatif", "3 000 € ÷ 350 € ≈ 8,6 mois"]])}<p>Si le gain net est nul ou négatif, il n’existe pas de délai d’amortissement sur ces hypothèses. Comparez les offres dans notre ${link("outils", "guide des outils et des postes de coût")}, en intégrant la formation et le temps interne de mise en place.</p>` },
      { id: "erreurs", title: "Quels défauts doivent bloquer la mise en production ?", html: `<p>Un total qui ne rejoint pas la balance, un compte sans mapping, une conversion de devise non documentée ou une actualisation silencieusement interrompue sont des motifs d’arrêt. Le dispositif doit afficher la date de ses données et la liste des exceptions, même lorsque le graphique paraît cohérent.</p><p>Dans le <a href="/ressources/cas-clients/opti-digital-structuration-financement">cas Iter Advisors Opti Digital</a>, les livrables documentés concernent notamment la migration ERP, le reporting et la clôture. Ils illustrent les fondations du chantier ; la fiche ne revendique pas de gain lié à l’IA.</p>` },
      { id: "commencer", title: "Que préparer pour un premier cadrage ?", html: `<p>Réunissez un reporting finalisé, sa balance source, la liste des retraitements et le temps passé par tâche. Sur cette base, un <a href="/daf-externalise">DAF externalisé</a> peut prioriser les automatisations et définir les contrôles avec l’équipe comptable. Le ${link("chatgpt-finance", "guide ChatGPT pour la finance")} fournit ensuite un exercice de commentaire des écarts.</p>` },
    ],
    faq: [
      {question: "Faut-il de l’IA pour automatiser un reporting ?", answer: "Non. La collecte, les agrégations et une partie des contrôles peuvent reposer sur des connecteurs et des règles déterministes. L’IA peut compléter ce dispositif pour la rédaction ou l’analyse documentaire."},
      {question: "Peut-on garantir une clôture à J+5 ?", answer: "Non. Le délai dépend aussi de la réception des pièces, des stocks, des retraitements et des validations. Fixez un objectif après avoir mesuré le processus existant."},
      {question: "Quand l’automatisation est-elle rentable ?", answer: "Lorsque la valeur du temps réellement libéré et les autres gains mesurables dépassent les coûts de mise en place et d’exploitation. Un nombre de jours de reporting ne suffit pas, seul, à conclure."},
    ], sources: ["usVenture", "pennylane", "powerBi"], related: ["feuille-de-route-90-jours", "chatgpt-finance"],
  },
  "chatgpt-finance": {
    label: "ChatGPT pour la finance",
    title: "ChatGPT pour la finance : exemples, prompts et contrôles",
    description: "Trois exercices pour une équipe finance : commentaire d’écarts, relance de pièces et préparation du board. Prompts, résultats attendus et confidentialité.",
    dek: "ChatGPT peut aider une direction financière à commenter un budget, préparer une demande de pièces et analyser un fichier avec des outils de calcul. La fiabilité dépend des données fournies, des vérifications et du contexte : une réponse fluide ne prouve pas qu’un chiffre est juste.",
    published: "2026-09-01", image: financeImage,
    summary: ["Les exemples ci-dessous sont pédagogiques et utilisent des données fictives.", "Demandez les étapes du calcul et vérifiez les résultats dans votre outil de référence.", "Choisissez un environnement autorisé avant de transférer des données de l’entreprise."],
    sections: [
      {id:"cas-usage", title:"Comment commenter un écart budget/réel ?", html:`<p>Voici un exemple fictif en milliers d’euros. Les charges sont présentées en montants positifs ; le solde est une différence simplifiée, pas un EBITDA comptable.</p>${table("Jeu de données fictif : un mois, une entité, montants en k€", ["Indicateur", "Budget", "Réel", "Écart réel − budget"], [["Chiffre d’affaires", "200", "180", "−20 (−10 %)"], ["Charges", "150", "155", "+5 (+3,33 %)"], ["Solde simplifié CA − charges", "50", "25", "−25 (−50 %)"]])}<p><strong>Prompt à adapter :</strong></p><blockquote><p>À partir de ce tableau fictif en k€, rédige un commentaire de 120 mots maximum. Reprends les écarts calculés. Distingue les faits, les hypothèses et les questions à poser. N’invente aucune cause ni donnée absente. Termine par deux questions pour le responsable commercial et le responsable des charges.</p></blockquote><p><strong>Résultat attendu :</strong> constater que la baisse du CA et la hausse des charges réduisent le solde. Une perte de client, une hausse salariale ou un effet saisonnier doivent rester des hypothèses tant que vous ne les avez pas documentés. Un pourcentage avec un budget nul doit être indiqué comme non calculable.</p><p>Le modèle de données et les contrôles amont sont décrits dans ${link("automatiser-reporting-financier", "le guide du reporting automatisé")}.</p>`},
      {id:"pieces", title:"Comment préparer une demande de pièces plus précise ?", html:`<p>Fournissez le type de document attendu, la période et la raison exacte du rejet. Retirez les identifiants inutiles avant le test. Le ${source("armanino", "cas Armanino publié par Anthropic")} décrit un outil de rédaction des explications envoyées lorsqu’une pièce d’audit est incorrecte.</p><blockquote><p>Rédige une demande courtoise de moins de 100 mots. Pièce reçue : balance de juin. Pièce attendue : balance de juillet, après clôture. Explique la différence et précise le document à transmettre. N’ajoute ni montant, ni échéance, ni engagement non fourni.</p></blockquote><p>Vérifiez le destinataire, la pièce et la période avant l’envoi. Ce brouillon ne doit pas déclencher automatiquement une relance. Le ${link("retours-experience", "détail du cas et de ses limites")} distingue l’outil déployé des gains estimés par l’éditeur.</p>`},
      {id:"board", title:"Comment préparer les questions du conseil ?", html:`<p>Travaillez sur une version validée du reporting, après autorisation d’accès. Définissez la décision à préparer : recrutement, financement ou arbitrage de dépenses.</p><blockquote><p>À partir des seuls indicateurs et commentaires fournis, propose cinq questions qu’un administrateur pourrait poser. Pour chacune, cite la ligne ou le passage qui la motive, précise l’information manquante et distingue risque constaté et hypothèse. Ne recommande aucune décision sans les données nécessaires.</p></blockquote><p>Rapprochez les questions du <a href="/ressources/blog/flux-de-tresorerie">prévisionnel de trésorerie</a>. Une rentabilité positive n’exclut pas un besoin de financement à court terme.</p>`},
      {id:"proscrire", title:"ChatGPT peut-il calculer et analyser un fichier Excel ?", html:`<p>Oui : ${source("dataAnalysis", "la documentation OpenAI sur l’analyse de données")} décrit l’analyse de fichiers et l’utilisation de code. Il faut distinguer le texte généré d’un calcul exécuté par un outil. Demandez le code ou les formules, les colonnes utilisées et les exclusions.</p><p>Vérifiez séparément les totaux, les signes, les devises, les lignes vides et les doublons. Rejouez le calcul dans Excel, un script contrôlé ou la BI. La présence de code ne valide ni les hypothèses ni la qualité du fichier. Ne déléguez pas la signature des comptes, l’approbation d’un paiement ou une décision fiscale à la réponse du modèle.</p>`},
      {id:"charte", title:"Quelles données et quelle offre utiliser ?", html:`<p>Commencez sur des données fictives ou publiques. Pour les données internes, l’entreprise doit autoriser l’outil, ses accès et la finalité du traitement. Retirer un nom ne suffit pas toujours à anonymiser un fichier : des montants, dates et fonctions peuvent permettre de retrouver une personne.</p><p>${source("openaiData", "OpenAI documente le non-entraînement par défaut des données Business, Enterprise et API")}. Cela ne signifie pas absence de conservation ni autorisation de transmettre tout document. Contrôlez également les droits, la durée de conservation, les connecteurs et les conditions contractuelles. La validation du DPO ou du responsable de la sécurité dépend du contexte de l’entreprise.</p><p>Inscrivez dans votre charte les usages autorisés, les données exclues, le responsable de relecture et la conduite à tenir en cas d’erreur. Utilisez notre ${link("llm-finance", "grille de choix des LLM")} pour comparer les environnements sur vos propres documents.</p>`},
    ],
    faq:[{question:"Peut-on utiliser ChatGPT pour un prévisionnel de trésorerie ?",answer:"Il peut aider à structurer les hypothèses et à préparer un calcul avec des outils. Les échéances, les encaissements attendus et les scénarios doivent être documentés, puis vérifiés dans le modèle financier de référence."},{question:"Une offre payante garantit-elle la confidentialité ?",answer:"Le prix ne suffit pas. Il faut vérifier le contrat de l’offre, les réglages, la conservation, les accès et les intégrations, puis respecter la politique de l’entreprise."},{question:"Ces prompts décrivent-ils des missions Iter Advisors ?",answer:"Non. Les exercices utilisent des données fictives. Les cas publics cités sont attribués à leurs éditeurs et séparés des missions Iter documentées."}],
    sources:["dataAnalysis","openaiData","armanino"], related:["llm-finance","retours-experience"],
  },
  "llm-finance": {
    label:"Choisir un LLM pour la finance", title:"LLM en finance : comparer ChatGPT, Claude et Gemini",
    description:"Choisir un LLM pour la finance : grille de test, sources, calculs, confidentialité et intégration. Un protocole de comparaison sans classement artificiel.",
    dek:"Le bon LLM pour une équipe finance est celui qui réussit un test métier reproductible dans un environnement autorisé. Comparez la qualité des réponses, la traçabilité des chiffres et le temps de correction, avec les mêmes documents et les mêmes consignes.",
    published:"2026-09-01", image:financeImage,
    summary:["Un modèle, l’application qui l’héberge et ses connecteurs sont trois éléments à évaluer.","Comparez les réponses sur un dossier identique, avec un corrigé préparé avant le test.","Conservez la version de l’outil et les réglages : les offres évoluent."],
    sections:[
      {id:"comparatif",title:"Quels critères comparer entre les assistants ?",html:`<p>ChatGPT, Claude et Gemini ne se réduisent pas à un style de rédaction. Les fonctions disponibles dépendent de l’offre, des réglages administrateur et des outils connectés. Cette grille est une méthode de sélection, pas un benchmark réalisé par Iter.</p>${table("Grille à remplir pour chaque environnement testé",["Critère","Épreuve","Preuve à conserver"],[["Calcul","Recalculer un tableau avec avoirs, doublons et budget nul","Formules ou code, résultat rapproché du corrigé"],["Documents","Retrouver cinq clauses dans un dossier","Nom du fichier, page et extrait exact"],["Contexte","Expliquer un écart dont la cause n’est pas fournie","Distinction entre fait et hypothèse"],["Intégration","Lire uniquement les dossiers autorisés","Vérification des droits et des actions possibles"],["Coût","Mesurer le temps du test et de sa correction","Licences, consommation et temps de revue"]])}${table("Trois environnements : fonctions documentées et questions de test",["Environnement","Point de départ documenté","Question à vérifier"],[["ChatGPT",source("dataAnalysis","Analyse de fichiers et calculs avec du code"),"Les opérations, exclusions et fichiers de sortie sont-ils vérifiables ?"],["Claude dans une application métier",source("hebbia","Analyse de dossiers dans le cas Hebbia"),"L’application choisie conserve-t-elle les références aux pièces ?"],["Gemini dans Data Studio",source("googleBi","Assistance aux questions, champs calculés et présentations"),"Les fonctions sont-elles disponibles dans votre offre et votre contexte de données ?"]])}<p>Ces exemples portent sur des produits et intégrations différents. Ils ne constituent pas un classement de la qualité des modèles. Comparez ensuite les configurations réellement accessibles à votre équipe.</p><p>ChatGPT documente ${source("dataAnalysis","l’analyse de fichiers avec des outils de calcul")}. Pour chaque autre environnement candidat, demandez la même démonstration sur le jeu de données de l’entreprise, sans présumer d’une qualité équivalente.</p>`},
      {id:"font-bien",title:"Comment organiser un test comparatif utile ?",html:`<ol><li>Préparez un dossier autorisé : tableau d’écarts, procédure de clôture et pièces documentaires.</li><li>Écrivez un corrigé avec les chiffres attendus, les sources et les questions sans réponse.</li><li>Soumettez la même consigne à chaque outil et conservez les réponses complètes.</li><li>Notez les erreurs, les références inventées, les omissions et les minutes de correction.</li><li>Répétez les cas sensibles : une seule bonne réponse ne démontre pas la fiabilité.</li></ol><p>Un résultat exact sans référence vérifiable n’est pas suffisant pour une note d’audit. Écartez un environnement si des droits trop larges sont nécessaires pour faire fonctionner le test. Les ${link("chatgpt-finance","exercices du guide ChatGPT")} offrent un point de départ reproductible.</p>`},
      {id:"cas",title:"Que montre le cas Hebbia sur les dossiers financiers ?",html:`<p>${source("hebbia","Anthropic décrit l’utilisation de Claude par Hebbia")} pour l’analyse de documents financiers et juridiques. Claude intervient dans une plateforme qui organise les documents et les tâches : l’application ne se limite pas à une conversation isolée.</p><p>Pour une PME, la leçon à tester est la traçabilité documentaire. Demandez pour chaque affirmation le fichier et le passage justificatif. Le chiffre de réduction de temps lié au cache affiché par l’éditeur ne doit pas être interprété comme un gain de productivité d’une direction financière. Consultez les ${link("retours-experience","cas et leurs périmètres")}.</p>`},
      {id:"jamais",title:"Quelles décisions doivent rester validées par un responsable ?",html:`<p>La validation des hypothèses de budget, les provisions, l’approbation des paiements et la communication aux investisseurs engagent l’entreprise. Un assistant peut préparer une proposition ; il faut garder un responsable identifié et une piste de contrôle.</p><p>Pour une <a href="/ressources/blog/checklist-due-diligence-levee-de-fonds">due diligence financière</a>, utilisez le modèle pour repérer les pièces manquantes ou préparer les questions. L’absence de signalement par le modèle ne prouve pas l’absence de risque. La revue finale porte aussi sur ce qui n’a pas été fourni.</p>`},
      {id:"confidentialite",title:"Que vérifier avant de connecter les données financières ?",html:`<p>Documentez qui peut lire quoi, quelles actions sont possibles, où les données sont conservées et comment retirer un accès. Les engagements ${source("openaiData","OpenAI pour les données professionnelles")} et ${source("anthropicData","Anthropic sur l’entraînement")} doivent être lus pour l’offre réellement retenue. Ne transposez pas une condition d’un produit à un autre.</p><p>Au pilote, privilégiez la lecture seule et limitez le dossier accessible. Un <a href="/daf-externalise">DAF externalisé</a> peut définir le besoin métier avec l’IT et les responsables des données. La ${link("feuille-de-route-90-jours","feuille de route")} relie cette sélection aux étapes du déploiement.</p>`},
    ], faq:[{question:"Existe-t-il un meilleur LLM pour toutes les directions financières ?",answer:"Non. Le choix dépend du dossier, des outils disponibles, des accès, de la qualité attendue et du coût de vérification. Comparez les environnements sur les mêmes tâches."},{question:"Un LLM peut-il faire des calculs ?",answer:"Un assistant peut utiliser du code, un tableur ou d’autres outils de calcul. Vérifiez les opérations exécutées et leurs hypothèses ; un nombre généré dans du texte n’est pas une preuve de calcul."},{question:"Comment mesurer la qualité d’un résumé financier ?",answer:"Comparez-le à un corrigé : chiffres exacts, sources retrouvables, absence de cause inventée, points matériels couverts et temps de correction. Testez également les informations absentes du dossier."}],sources:["dataAnalysis","hebbia","googleBi","openaiData","anthropicData"],related:["chatgpt-finance","outils"],
  },
  "outils": {
    label:"Outils de reporting et d’IA",title:"Outils IA et reporting financier : comment choisir pour une PME",
    description:"Comparez reporting, connecteurs et assistants IA : critères, coût complet, licences et questions à poser avant achat. Liens vers les documentations éditeur.",
    dek:"Choisir un outil financier commence par les données à exploiter et les contrôles attendus. Évaluez séparément le logiciel comptable, la connexion des données, le reporting et l’assistant IA : acheter une licence ne relie pas automatiquement ces quatre éléments.",
    published:"2026-09-01",image:financeImage,
    summary:["Une API disponible n’est pas un connecteur prêt à l’emploi.","Incluez les lecteurs des rapports, la maintenance et le temps interne dans le budget.","Demandez une démonstration sur un export autorisé avant de vous engager."],
    sections:[
      {id:"reporting",title:"Quel outil pour quel besoin financier ?",html:`${table("Les couches d’un dispositif financier",["Besoin","Option à évaluer","Vérification préalable"],[["Un reporting simple dans l’outil existant","Module comptable, Excel ou tableur déjà maîtrisé","Indicateurs disponibles et export du détail"],["Plusieurs sources et tableaux de bord partagés","Power BI ou outil BI équivalent","Licences des lecteurs, modèle de données et rafraîchissement"],["Un reporting dans l’environnement Google","Data Studio, anciennement Looker Studio","Connecteurs, propriété des rapports et éventuelle offre Pro"],["Des commentaires et analyses documentaires","Assistant IA dans une offre autorisée","Sources, confidentialité et temps de correction"]])}<p>La ${source("powerBi","grille Microsoft Power BI")} distingue création et partage. La ${source("googleBi","documentation Google Data Studio Pro")} précise les fonctions de gestion des contenus et de collaboration. La version gratuite d’un outil ne rend pas gratuits les connecteurs ou l’exploitation du reporting.</p>`},
      {id:"connecteur",title:"API, connecteur natif ou développement : quelle différence ?",html:`<p>Une API donne un accès programmatique à certaines données. Le connecteur prend en charge la récupération, les transformations et les erreurs. Vérifiez la couverture des écritures, l’historique, les quotas, les droits et les conditions du plan souscrit.</p><p>${source("pennylane","Pennylane documente ses API et leurs modes d’accès")}. Cela ne démontre pas qu’une connexion vers votre BI soit incluse, gratuite ou suffisante. Notre <a href="/ressources/outils/pennylane">fiche Pennylane</a> aide à situer l’outil ; exigez ensuite un test sur le périmètre voulu.</p><ul><li>Un compte ajouté au plan comptable doit-il être remappé manuellement ?</li><li>Qui reçoit une alerte en cas d’échec du chargement ?</li><li>Peut-on réimporter une période sans créer de doublons ?</li><li>Comment récupérer les données et les règles en quittant le prestataire ?</li></ul>`},
      {id:"llm",title:"Comment choisir la couche IA ?",html:`<p>Définissez une tâche précise : commenter un écart, retrouver une clause ou rédiger une demande de pièce. Comparez le résultat avec celui produit sans IA, en incluant le temps de revue. Le ${link("llm-finance","protocole de comparaison des LLM")} évite de choisir sur une démonstration préparée par un commercial.</p><p>Le ${source("armanino","cas Armanino")} illustre un outil ciblé sur les demandes de pièces d’audit. C’est une piste pour tester la rédaction, pas une justification pour confier toute la clôture à un assistant.</p>`},
      {id:"stack",title:"Faut-il changer toute la stack financière ?",html:`<p><strong>Petite équipe, une entité :</strong> vérifiez d’abord ce que l’outil existant permet d’exporter. Un fichier bien structuré et quelques contrôles peuvent suffire au pilote.</p><p><strong>PME multi-sources :</strong> le travail porte souvent sur les correspondances entre comptabilité, ventes et trésorerie. Un <a href="/daf-externalise">DAF externalisé pour PME</a> peut prioriser les flux à connecter.</p><p><strong>Groupe multi-entités :</strong> traitez les devises, les éliminations et les droits avant de comparer les interfaces. L’IA ne remplace pas les règles de consolidation. Pour une startup SaaS, consultez aussi notre <a href="/ressources/blog/stack-financier-saas-series-a">guide de la stack financière en Series A</a>.</p>`},
      {id:"regle",title:"Quels postes inclure dans le coût complet ?",html:`<p>Demandez un devis séparant les licences, la connexion et la reprise d’historique, le modèle de données, la formation, l’exploitation et la réversibilité. Un devis de projet peut être pertinent s’il explicite ces postes.</p><p>Au 5 septembre 2026, Microsoft affiche Power BI Pro à <strong>12,10 € HT par utilisateur et par mois, avec paiement annuel</strong>. Ce tarif concerne la licence, pas la mise en place du reporting. Vérifiez le prix et les droits au moment de l’achat sur la ${source("powerBi","page Microsoft")}. Les assistants et leurs fonctions évoluent : faites confirmer les limites de l’offre retenue.</p><p>Utilisez l’${link("automatiser-reporting-financier", "exemple de calcul du ROI")} pour comparer les coûts au temps réellement récupéré. Le bon point de départ est un pilote à périmètre limité, avec un export de secours.</p>`},
    ],faq:[{question:"Une API comptable suffit-elle à automatiser le reporting ?",answer:"Non. Il faut aussi organiser la récupération des données, leur transformation, les contrôles, les alertes et la maintenance. Vérifiez les accès et les fonctions incluses dans le contrat."},{question:"Power BI est-il gratuit ?",answer:"Microsoft distingue un compte gratuit et des offres payantes pour certains usages de partage ou de capacité. Le besoin de licences dépend des producteurs et des lecteurs. Le coût d’intégration reste à prévoir."},{question:"Faut-il acheter un assistant IA dès le début ?",answer:"Pas nécessairement. Un pilote de collecte et de reporting peut fonctionner sans IA. Ajoutez l’assistant lorsque la tâche et son gain net après relecture sont établis."}],sources:["powerBi","pennylane","googleBi","armanino"],related:["automatiser-reporting-financier","llm-finance"],
  },
  "feuille-de-route-90-jours": {
    label:"Feuille de route à 90 jours",title:"IA et finance : feuille de route à 90 jours pour un pilote",
    description:"Un plan de déploiement IA et reporting pour PME : responsables, livrables, critères de passage, mesure des gains et retour au processus manuel si nécessaire.",
    dek:"En 90 jours, l’objectif est de tester un processus financier sur un périmètre maîtrisé et de décider s’il mérite d’être étendu. Le calendrier dépend des accès, du rythme des clôtures et de la qualité des données. Il ne garantit ni un gain de productivité ni une clôture à J+5.",
    published:"2026-09-01",image:financeImage,
    summary:["Un processus prioritaire, un responsable métier et une référence avant/après.","La progression dépend de critères de qualité, pas seulement de dates.","Deux clôtures mensuelles ne tiennent pas forcément dans le dernier mois : prolongez la validation si nécessaire."],
    sections:[
      {id:"s1-3",title:"Semaines 1 à 3 : cadrer et mesurer le point de départ",html:`<p>Choisissez une tâche fréquente et observable, par exemple les rapprochements d’un compte ou la préparation d’un reporting. Chronométrez la collecte, le traitement et la relecture. Notez les erreurs détectées et les demandes de correction.</p><p><strong>Responsable :</strong> DAF ou contrôleur de gestion, avec les utilisateurs du processus. <strong>Livrable :</strong> fiche de périmètre, dictionnaire des données, liste des accès et indicateurs avant projet. <strong>Critère de passage :</strong> le dirigeant valide le besoin et un responsable peut expliquer le résultat de référence.</p><p>Le <a href="/ressources/cas-clients/opti-digital-structuration-financement">cas Opti Digital</a> illustre la structuration ERP, reporting et clôture qui peut précéder une couche IA.</p>`},
      {id:"s4-6",title:"Semaines 4 à 6 : connecter et comparer",html:`<p>Connectez une seule source en lecture seule ou commencez par un export contrôlé. Comparez l’extraction au fichier de référence : nombre de lignes, totaux, périodes et entités. Ajoutez une alerte sur les chargements incomplets.</p><p><strong>Responsables :</strong> IT ou intégrateur pour la connexion ; finance pour le mapping. <strong>Livrable :</strong> tableau des écarts et procédure de reprise. <strong>Critère de passage :</strong> les écarts sont expliqués et approuvés, les droits sont limités, le retour à l’export manuel est testé.</p><p>Préparez les questions du ${link("outils","guide de sélection des outils et connecteurs")}, notamment les quotas, l’historique et la maintenance.</p>`},
      {id:"s7-10",title:"Semaines 7 à 10 : construire le reporting et tester l’assistant",html:`<p>Produisez le tableau de bord sur le périmètre retenu. Affichez la date des données et les exceptions. Si la couche de calcul est validée, testez la rédaction d’un commentaire à partir des seuls écarts approuvés.</p><p><strong>Responsable :</strong> finance, avec le référent sécurité pour les données confiées à l’assistant. <strong>Livrable :</strong> reporting rapproché, corrigé du test et temps de relecture. <strong>Critère de passage :</strong> aucun écart inexpliqué matériel, aucune cause inventée acceptée dans le document final.</p><p>Utilisez les ${link("chatgpt-finance","prompts et le jeu de données fictif")} avant tout test sur des chiffres internes.</p>`},
      {id:"s11-13",title:"Semaines 11 à 13 : décider, documenter et former",html:`<p>Comparez le temps complet avant et après, les erreurs, les coûts et les usages effectifs. Formalisez qui traite les exceptions et qui peut modifier les règles. Formez un second utilisateur pour éviter de dépendre du concepteur.</p><p><strong>Livrable :</strong> décision de poursuite, de correction ou d’arrêt, avec procédure et budget. <strong>Critère de passage :</strong> un utilisateur autre que le concepteur sait exécuter le processus et retrouver les justificatifs. Pour une clôture mensuelle, prolongez la phase si deux cycles comparables n’ont pas encore été observés.</p>`},
      {id:"derape",title:"Quels indicateurs suivre et quand arrêter ?",html:`${table("Tableau de recette du pilote",["Indicateur","Mesure","Signal d’arrêt ou de correction"],[["Temps total","Production + contrôles + corrections","Le gain disparaît à la relecture"],["Fiabilité","Écarts au corrigé et anomalies non détectées","Un écart matériel reste inexpliqué"],["Exploitation","Chargements réussis et délais de reprise","Données périmées sans alerte"],["Adoption","Exécution autonome par les utilisateurs","Seul le prestataire peut produire le résultat"],["Économie","Gain net et investissement initial","Coûts supérieurs aux gains retenus"]])}<p>Les seuils doivent être fixés au cadrage avec le responsable financier. Le ${link("automatiser-reporting-financier","calcul du ROI du reporting")} distingue capacité libérée et économies de trésorerie.</p>`},
      {id:"pilote",title:"Quel rôle pour le DAF externalisé ?",html:`<p>Le <a href="/daf-externalise">DAF externalisé</a> définit les indicateurs, valide les contrôles et arbitre le périmètre. L’IT sécurise les accès et les connexions ; l’équipe comptable vérifie les règles ; le dirigeant décide des objectifs. Cette coopération doit être écrite avant le choix de l’outil.</p><p>Pour préparer le cadrage, apportez un reporting approuvé, la liste de vos logiciels et un relevé du temps passé. Les ${link("retours-experience","cas documentés")} donnent des points de comparaison, à adapter à vos volumes et à votre organisation.</p>`},
    ],faq:[{question:"Que doit-on avoir obtenu au bout de 90 jours ?",answer:"Un pilote évalué, des contrôles documentés et une décision sur la suite. Un déploiement généralisé n’est pas obligatoire : arrêter un cas non rentable est un résultat utile."},{question:"Pourquoi prolonger la validation après 90 jours ?",answer:"Le calendrier des clôtures peut ne pas laisser assez de cycles comparables. Il vaut mieux observer les cycles nécessaires que valider à une date arbitraire."},{question:"Qui doit piloter le projet ?",answer:"Un responsable finance porte les règles métier, avec l’IT, les utilisateurs, l’expert-comptable et les responsables des données selon le périmètre. Le dirigeant arbitre le budget et les objectifs."}],sources:["pennylane","dataAnalysis","openaiData"],related:["automatiser-reporting-financier","retours-experience"],
  },
  "retours-experience": {
    label:"Cas réels et retours d’expérience",title:"IA en finance : cas réels, résultats publiés et limites",
    description:"U.S. Venture, Armanino, Hebbia : trois cas IA documentés et leur portée pour une PME. Avec Opti Digital, mission Iter de structuration financière distincte.",
    dek:"Trois cas publics montrent des usages précis de l’IA en finance : rapprochements, demandes de pièces et analyse documentaire. Nous indiquons qui publie chaque résultat, ce qui est mesuré et ce qu’une PME peut tester. Ces entreprises ne sont pas présentées comme des clients Iter Advisors.",
    published:"2026-09-05",image:financeImage,
    summary:["Les résultats de cas éditeur ne constituent ni un audit indépendant ni une promesse de gain.","Les applications proposées pour une PME sont notre lecture des cas, à tester localement.","Le cas Iter Opti Digital documente une structuration financière, sans gain IA revendiqué."],
    sections:[
      {id:"us-venture",title:"U.S. Venture : rapprocher les cartes et les relevés bancaires",html:`<p><strong>Cas publié :</strong> le 28 janvier 2025, ${source("usVenture","Microsoft décrit le déploiement chez U.S. AutoForce, division de U.S. Venture")}. L’équipe utilise Copilot for Finance sur deux rapprochements récurrents. L’éditeur rapporte quatre semaines de mise en place et plus de 30 heures économisées par mois. Une responsable déclare 80 % de réduction du temps sur ses rapprochements US Bank.</p><p><strong>Portée :</strong> ces mesures concernent des tâches précises d’un groupe déjà équipé de Dynamics 365. Elles ne décrivent pas la totalité d’une clôture et ne sont pas un benchmark indépendant.</p><p><strong>Application proposée pour une PME :</strong> tester un compte sur une période close, conserver les rapprochements ambigus dans une file de revue et comparer le temps de traitement plus contrôle. Notre ${link("automatiser-reporting-financier","méthode de reporting automatisé")} détaille les étapes.</p>`},
      {id:"armanino",title:"Armanino : expliquer les pièces manquantes ou incorrectes",html:`<p><strong>Cas publié :</strong> ${source("armanino","Anthropic présente un outil construit par Armanino avec Claude sur Amazon Bedrock")}. Il prépare des notes expliquant pourquoi une pièce d’audit ne convient pas et quel document le client doit fournir. Le cas indique deux semaines pour passer de l’idée à la production de ce premier outil.</p><p><strong>Portée :</strong> la page annonce notamment une réduction de 65 % du temps de rédaction, mais qualifie ces bénéfices d’estimés ou attendus dans son texte. Nous ne retenons donc pas ce chiffre comme un gain mesuré et garanti.</p><p><strong>Application proposée pour une PME :</strong> préparer un brouillon à partir d’un motif de rejet validé. Mesurer le temps de rédaction et les allers-retours, puis faire approuver le message. Un ${link("chatgpt-finance#pieces","exemple de prompt de demande de pièces")} permet de tester cette approche.</p>`},
      {id:"hebbia",title:"Hebbia : organiser l’analyse de dossiers financiers",html:`<p><strong>Cas publié :</strong> ${source("hebbia","Anthropic décrit l’utilisation de Claude dans la plateforme Hebbia")}, qui traite des documents complexes pour des professionnels de la finance et du droit.</p><p><strong>Portée :</strong> il s’agit d’un modèle intégré à une plateforme documentaire. Les indications chiffrées du bandeau et du corps du cas diffèrent. Elles concernent le cache et les temps de réponse techniques ; nous n’en tirons aucun pourcentage de gain de productivité financière.</p><p><strong>Application proposée pour une PME :</strong> construire une matrice « question, réponse, fichier, passage justificatif, validation ». Commencer avec une data room réduite et des droits limités. Notre ${link("llm-finance","grille de test des LLM")} précise comment vérifier les références et les omissions.</p>`},
      {id:"opti-digital",title:"Opti Digital : les fondations financières d’une mission Iter",html:`<p>La <a href="/ressources/cas-clients/opti-digital-structuration-financement">mission Iter Advisors auprès d’Opti Digital</a> documente la migration ERP, le reporting mensuel, les procédures de clôture et l’accompagnement au financement. Le témoignage de la dirigeante décrit cinq années de collaboration à sa publication, le 12 novembre 2025.</p><p>Ce cas montre le travail d’organisation préalable à l’automatisation. Il n’établit pas l’utilisation d’un modèle IA ni un gain de productivité attribuable à l’IA. La fiche renvoie au témoignage public et précise les limites des résultats disponibles.</p><p>Consultez aussi <a href="/ressources/cas-clients/seasonly-marge-par-canal-bfr">le pilotage de marge par canal chez Seasonly</a> pour définir les indicateurs à produire avant de choisir la technologie.</p>`},
      {id:"transposer",title:"Comment transposer ces cas sans copier leurs promesses ?",html:`${table("Décider du premier pilote",["Votre problème","Cas utile","Mesure locale"],[["Rapprochements longs","U.S. Venture","Temps complet et taux d’exceptions"],["Demandes de pièces imprécises","Armanino","Temps de rédaction et allers-retours"],["Dossiers volumineux","Hebbia","Exactitude des références et omissions"],["Données dispersées","Opti Digital, structuration financière","Fiabilité du reporting et procédure de clôture"]])}<p>La ${link("feuille-de-route-90-jours","feuille de route à 90 jours")} aide à transformer une idée en test mesurable. Un <a href="/daf-externalise">DAF externalisé</a> peut en piloter le cadrage et les contrôles avec vos équipes.</p>`},
    ],faq:[{question:"Ces entreprises sont-elles toutes clientes d’Iter Advisors ?",answer:"Non. U.S. Venture, Armanino et Hebbia sont des cas publics publiés par des éditeurs. Opti Digital est présenté séparément comme une mission Iter de structuration financière."},{question:"Les gains publiés sont-ils reproductibles dans une PME ?",answer:"Ils ne sont pas garantis. Les volumes, l’environnement technique et les coûts de contrôle diffèrent. Mesurez le résultat sur un périmètre comparable avant d’étendre le dispositif."},{question:"Pourquoi distinguer résultat mesuré et bénéfice estimé ?",answer:"Une estimation exprime un potentiel. Un résultat mesuré doit préciser le processus, la période, le point de départ et la méthode. Lorsque ces éléments manquent, le chiffre ne suffit pas à établir un ROI."}],sources:["usVenture","armanino","hebbia"],related:["feuille-de-route-90-jours","automatiser-reporting-financier"],
  },
};
export const IA_GUIDE_SLUGS = Object.keys(IA_GUIDES);
