import type { Locale } from "@/lib/i18n";

/** Short server-rendered interface copy; no guide corpus in client components. */
const translations: Record<"en" | "es", Record<string, string>> = {
  "en": {
    "IA & Finance": "AI & Finance",
    "IA et finance : cas réels et guides pratiques pour les PME": "AI and finance: real cases and practical guides for SMEs",
    "Reporting automatisé, ChatGPT, choix des outils et cas documentés : une méthode pour appliquer l’IA à la finance d’une PME avec des résultats vérifiables.": "Automated reporting, ChatGPT, tool selection and documented cases: a method for applying AI to SME finance with verifiable results.",
    "L’IA peut aider une équipe finance à préparer des commentaires, traiter des documents et repérer des écarts. Les connexions et les règles de calcul restent les fondations du reporting. Ces guides vous aident à choisir un premier usage, le tester et vérifier son intérêt avant de l’étendre.": "AI can help finance teams prepare commentary, process documents and identify variances. Connections and calculation rules remain the foundations of reporting. These guides help you choose a first use case, test it and verify its value before expanding.",
    "Ressources": "Resources",
    "Par": "By",
    "Mise à jour du": "Updated on",
    "Sommaire IA et finance": "AI and finance contents",
    "Par où commencer": "Where to start",
    "Les six guides": "The six guides",
    "Cas et méthode": "Cases and method",
    "Accompagnement DAF": "CFO support",
    "Quel est votre point de départ ?": "Where are you starting from?",
    "Mon reporting prend trop de temps": "My reporting takes too long",
    "Cartographier les tâches et calculer le ROI": "Map the tasks and calculate ROI",
    "Je veux tester l’IA sur une tâche précise": "I want to test AI on a specific task",
    "Essayer les prompts sur des données fictives": "Try prompts on fictitious data",
    "Je cherche des preuves avant d’investir": "I need evidence before investing",
    "Lire les cas publics et leurs limites": "Read public cases and their limitations",
    "Je dois organiser le déploiement": "I need to organise deployment",
    "Définir le pilote et les critères de validation": "Define the pilot and acceptance criteria",
    "Six guides pour passer du besoin au pilote": "Six guides from need to pilot",
    "Guide": "Guide",
    "Quelles preuves trouverez-vous dans cette section ?": "What evidence will you find in this section?",
    "Les": "The",
    "cas publics U.S. Venture, Armanino et Hebbia": "public U.S. Venture, Armanino and Hebbia cases",
    "sont attribués à Microsoft ou Anthropic. La lecture indique les tâches concernées et distingue les résultats rapportés des bénéfices estimés. Ces entreprises ne sont pas présentées comme des clients Iter.": "are attributed to Microsoft or Anthropic. The analysis identifies the tasks and distinguishes reported results from estimated benefits. These companies are not presented as Iter clients.",
    "Nos": "Our",
    "travaux documentés chez Opti Digital": "documented work at Opti Digital",
    "illustrent la structuration ERP, reporting et clôture. Aucun gain IA ne leur est attribué. Les prompts et le calcul de ROI proposés dans les guides sont des exercices fictifs, identifiés comme tels.": "illustrates ERP, reporting and closing structuring. No AI gain is attributed to it. Prompts and ROI calculations in the guides are clearly labelled fictitious exercises.",
    "Automatisation, IA et responsabilité : qui fait quoi ?": "Automation, AI and accountability: who does what?",
    "Un connecteur récupère les données. Des règles calculent les indicateurs. Un assistant peut préparer une analyse ou un commentaire. Le responsable financier contrôle les résultats et valide les décisions. Décrivez ces étapes séparément pour identifier les erreurs et mesurer le gain net de temps.": "A connector retrieves data. Rules calculate indicators. An assistant can prepare analysis or commentary. The finance owner checks results and approves decisions. Describe these stages separately to identify errors and measure the net time benefit.",
    "Pour comprendre les choix d’organisation, lisez": "To understand organisational choices, read",
    "le rôle du DAF dans une finance assistée par IA": "the CFO’s role in AI-assisted finance",
    ". Pour sélectionner les premières tâches, utilisez": ". To select the first tasks, use",
    "la grille de priorisation des tâches répétitives": "the repetitive-task prioritisation framework",
    "Un DAF pour cadrer et piloter le chantier": "A CFO to scope and lead the project",
    "Le": "The",
    "DAF externalisé": "Fractional CFO",
    "définit les indicateurs, organise les contrôles et coordonne l’équipe comptable avec les intervenants techniques. Pour préparer l’échange, identifiez votre reporting actuel, les logiciels utilisés et la tâche qui consomme le plus de temps.": "defines indicators, organises controls and coordinates the accounting team with technical contributors. To prepare the discussion, identify your current reporting, software and most time-consuming task.",
    "Échanger sur votre projet": "Discuss your project",
    "Cas et sources actualisés": "Cases and sources reviewed",
    "Tableaux de bord et analyse de données financières": "Dashboards and financial data analysis",
    "À retenir": "Key points",
    "Kit et exercice corrigé": "Kit and exercise with answer key",
    "Calculer le retour sur investissement": "Calculate the return on investment",
    "Questions fréquentes": "Frequently asked questions",
    "Échanger sur mon projet": "Discuss my project",
    "Cadrer votre projet avec un DAF": "Scope your project with a CFO",
    "Partagez votre besoin, les outils utilisés et les difficultés rencontrées. Nous pourrons préciser le périmètre, les livrables et les contrôles d’un accompagnement.": "Share your needs, tools and difficulties. We can clarify the scope, deliverables and controls for support.",
    "Découvrir notre offre de DAF externalisé": "Explore our Fractional CFO service",
    "Outils pratiques du guide": "Practical guide tools",
    "Accéder au kit corrigé": "Open the kit with answer key",
    "Calculer mon gain net": "Calculate my net benefit",
    "Quel gain net sur vos hypothèses ?": "What net benefit do your assumptions yield?",
    "Pour aller plus loin": "Further reading",
    "Demander un diagnostic": "Request an assessment",
    "min de lecture": "min read"
  },
  "es": {
    "IA & Finance": "IA y Finanzas",
    "IA et finance : cas réels et guides pratiques pour les PME": "IA y finanzas: casos reales y guías prácticas para pymes",
    "Reporting automatisé, ChatGPT, choix des outils et cas documentés : une méthode pour appliquer l’IA à la finance d’une PME avec des résultats vérifiables.": "Reporting automatizado, ChatGPT, herramientas y casos documentados: un método para aplicar IA a las finanzas de una pyme con resultados verificables.",
    "L’IA peut aider une équipe finance à préparer des commentaires, traiter des documents et repérer des écarts. Les connexions et les règles de calcul restent les fondations du reporting. Ces guides vous aident à choisir un premier usage, le tester et vérifier son intérêt avant de l’étendre.": "La IA puede ayudar a finanzas a preparar comentarios, tratar documentos y detectar desviaciones. Las conexiones y reglas de cálculo siguen siendo la base del reporting. Estas guías ayudan a elegir un primer uso, probarlo y verificar su interés antes de ampliarlo.",
    "Ressources": "Recursos",
    "Par": "Por",
    "Mise à jour du": "Actualizado el",
    "Sommaire IA et finance": "Índice de IA y finanzas",
    "Par où commencer": "Por dónde empezar",
    "Les six guides": "Las seis guías",
    "Cas et méthode": "Casos y método",
    "Accompagnement DAF": "Acompañamiento CFO",
    "Quel est votre point de départ ?": "¿Cuál es tu punto de partida?",
    "Mon reporting prend trop de temps": "Mi reporting requiere demasiado tiempo",
    "Cartographier les tâches et calculer le ROI": "Identificar tareas y calcular el ROI",
    "Je veux tester l’IA sur une tâche précise": "Quiero probar IA en una tarea concreta",
    "Essayer les prompts sur des données fictives": "Probar prompts con datos ficticios",
    "Je cherche des preuves avant d’investir": "Busco evidencias antes de invertir",
    "Lire les cas publics et leurs limites": "Leer casos públicos y sus límites",
    "Je dois organiser le déploiement": "Necesito organizar el despliegue",
    "Définir le pilote et les critères de validation": "Definir el piloto y los criterios de validación",
    "Six guides pour passer du besoin au pilote": "Seis guías para pasar de la necesidad al piloto",
    "Guide": "Guía",
    "Quelles preuves trouverez-vous dans cette section ?": "¿Qué evidencias encontrarás en esta sección?",
    "Les": "Los",
    "cas publics U.S. Venture, Armanino et Hebbia": "casos públicos de U.S. Venture, Armanino y Hebbia",
    "sont attribués à Microsoft ou Anthropic. La lecture indique les tâches concernées et distingue les résultats rapportés des bénéfices estimés. Ces entreprises ne sont pas présentées comme des clients Iter.": "se atribuyen a Microsoft o Anthropic. La lectura indica las tareas y distingue resultados comunicados de beneficios estimados. No se presentan como clientes de Iter.",
    "Nos": "Nuestros",
    "travaux documentés chez Opti Digital": "trabajos documentados en Opti Digital",
    "illustrent la structuration ERP, reporting et clôture. Aucun gain IA ne leur est attribué. Les prompts et le calcul de ROI proposés dans les guides sont des exercices fictifs, identifiés comme tels.": "ilustran estructuración ERP, reporting y cierre. No se les atribuye beneficio de IA. Los prompts y cálculos de ROI son ejercicios ficticios identificados como tales.",
    "Automatisation, IA et responsabilité : qui fait quoi ?": "Automatización, IA y responsabilidad: ¿quién hace qué?",
    "Un connecteur récupère les données. Des règles calculent les indicateurs. Un assistant peut préparer une analyse ou un commentaire. Le responsable financier contrôle les résultats et valide les décisions. Décrivez ces étapes séparément pour identifier les erreurs et mesurer le gain net de temps.": "Un conector recoge datos. Las reglas calculan indicadores. Un asistente prepara análisis o comentarios. El responsable financiero controla resultados y valida decisiones. Describe las etapas por separado para detectar errores y medir el tiempo neto recuperado.",
    "Pour comprendre les choix d’organisation, lisez": "Para entender las decisiones organizativas, lee",
    "le rôle du DAF dans une finance assistée par IA": "el papel del CFO en las finanzas asistidas por IA",
    ". Pour sélectionner les premières tâches, utilisez": ". Para elegir las primeras tareas, utiliza",
    "la grille de priorisation des tâches répétitives": "la tabla de priorización de tareas repetitivas",
    "Un DAF pour cadrer et piloter le chantier": "Un CFO para definir y dirigir el proyecto",
    "Le": "El",
    "DAF externalisé": "CFO externo",
    "définit les indicateurs, organise les contrôles et coordonne l’équipe comptable avec les intervenants techniques. Pour préparer l’échange, identifiez votre reporting actuel, les logiciels utilisés et la tâche qui consomme le plus de temps.": "define indicadores, organiza controles y coordina contabilidad y técnicos. Para preparar la conversación, identifica reporting actual, software y tarea que consume más tiempo.",
    "Échanger sur votre projet": "Hablar de tu proyecto",
    "Cas et sources actualisés": "Casos y fuentes revisados",
    "Tableaux de bord et analyse de données financières": "Cuadros de mando y análisis de datos financieros",
    "À retenir": "Puntos clave",
    "Kit et exercice corrigé": "Kit y ejercicio con solución",
    "Calculer le retour sur investissement": "Calcular el retorno de la inversión",
    "Questions fréquentes": "Preguntas frecuentes",
    "Échanger sur mon projet": "Hablar de mi proyecto",
    "Cadrer votre projet avec un DAF": "Definir tu proyecto con un CFO",
    "Partagez votre besoin, les outils utilisés et les difficultés rencontrées. Nous pourrons préciser le périmètre, les livrables et les contrôles d’un accompagnement.": "Comparte tu necesidad, herramientas y dificultades. Podremos precisar alcance, entregables y controles del acompañamiento.",
    "Découvrir notre offre de DAF externalisé": "Descubrir nuestro servicio de CFO externo",
    "Outils pratiques du guide": "Herramientas prácticas de la guía",
    "Accéder au kit corrigé": "Acceder al kit con solución",
    "Calculer mon gain net": "Calcular mi beneficio neto",
    "Quel gain net sur vos hypothèses ?": "¿Qué beneficio neto dan tus hipótesis?",
    "Pour aller plus loin": "Para saber más",
    "Demander un diagnostic": "Solicitar un diagnóstico",
    "min de lecture": "min de lectura"
  }
};
export function iaText(locale: Locale, source: string): string {
  if (locale === "fr") return source;
  const translated = translations[locale][source];
  if (translated === undefined) throw new Error(`Missing IA interface translation: ${source}`);
  return translated;
}
