import type { Locale } from '@/lib/i18n';
export const TOOL_HUB_COPY = {
  fr: {
    eyebrow: 'Le choix des outils vu par la direction financière', title: 'Outils financiers : avis et critères de DAF', intro: 'Quel logiciel choisir pour la comptabilité, le cash ou les dépenses ? Nos fiches distinguent retours d’usage confirmés et analyses documentaires. Elles vous aident à examiner les points forts, les limites et le coût complet avant de décider.', explore: 'Explorer les outils par besoin', stack: 'Préparer ma stack finance', maturity: 'Commencez par votre organisation', maturityIntro: 'La maturité des processus compte davantage qu’un seuil automatique de chiffre d’affaires.', stages: [
      ['Première organisation', 'Un socle simple et des données fiables', 'Comptabilité, factures, banque et justificatifs. Définissez qui contrôle les pièces et les droits de paiement avant d’ajouter des logiciels.', 'Changer quand les pièces manquantes et les ressaisies empêchent une clôture régulière.'],
      ['Activité en croissance', 'Relier cash, dépenses et reporting', 'Ajoutez une prévision entretenue, des circuits d’approbation et des indicateurs communs. Les connexions doivent être testées sur les flux réels.', 'Changer quand les prévisions arrivent trop tard ou que chaque reporting exige une nouvelle réconciliation.'],
      ['Multi-entités ou international', 'Un référentiel et des responsabilités partagés', 'ERP, trésorerie groupe et reporting nécessitent des règles de clôture, des droits et une reprise documentés. Chiffrez aussi la maintenance des interfaces.', 'Changer quand les sociétés ne peuvent plus produire des données comparables et traçables.'],
    ], signal: 'Signal de bascule', directory: 'Explorez les fiches outils', directoryIntro: 'Filtrez les outils selon votre besoin, puis examinez les profils adaptés, les limites et les conditions de déploiement.', field: 'Pennylane : un retour d’usage concret', fieldText: 'Iter utilise Pennylane depuis quatre ans, pour environ 50 % de ses clients. Notre point fort retenu : centraliser la comptabilité et préparer une précomptabilité propre. Notre réserve : un reporting encore limité pour certains besoins de pilotage.', fieldLink: 'Lire notre avis Pennylane', method: 'Une méthode transparente', methodText: 'Nous distinguons documentation de l’éditeur, critères de sélection et expérience confirmée du cabinet. Les prix sont reliés à leurs sources ; aucun score chiffré ni résultat client n’est inventé.', methodLink: 'Voir la méthodologie', french: '', comparisons: 'Approfondir une comparaison', contact: '/contact', methodHref: '/ressources/outils/methodologie', profile: '/a-propos/florent-greth', profileLabel: 'Florent Greth, intégration Pennylane',
  },
  en: {
    eyebrow: 'Finance tools from a CFO’s perspective', title: 'Finance tools: reviews and CFO selection criteria', intro: 'Which software fits your accounting, cash or expenses? Our guides distinguish confirmed firm experience from documentation-based analysis. Examine strengths, limitations and total cost before deciding.', explore: 'Explore tools by need', stack: 'Plan my finance stack', maturity: 'Start with your organisation', maturityIntro: 'Process maturity matters more than an automatic revenue threshold.', stages: [
      ['First finance setup', 'A simple foundation and reliable data', 'Accounting, invoices, banking and receipts. Define who checks documents and payment permissions before adding software.', 'Change when missing documents and repeated data entry prevent regular closes.'],
      ['Growing business', 'Connect cash, expenses and reporting', 'Add a maintained forecast, approval workflows and shared indicators. Test connections against real transactions.', 'Change when forecasts arrive too late or every report requires fresh reconciliation.'],
      ['Multi-entity or international', 'Shared definitions and responsibilities', 'ERP, group treasury and reporting require documented close rules, permissions and migration. Include interface maintenance in the budget.', 'Change when entities can no longer produce comparable, traceable data.'],
    ], signal: 'When to reconsider', directory: 'Explore the software guides', directoryIntro: 'Filter tools by business need, then examine suitable profiles, limitations and deployment requirements. Detailed reviews are currently in French.', field: 'Pennylane: confirmed experience', fieldText: 'Iter has used Pennylane for four years, for around 50% of its clients. The main strength we identify is centralised accounting and clean pre-accounting. Our reservation is reporting that remains limited for some management needs.', fieldLink: 'Read our Pennylane review', method: 'A transparent method', methodText: 'We distinguish publisher documentation, selection criteria and confirmed firm experience. Prices link to their sources; no numerical score or client result is invented.', methodLink: 'Read the methodology', french: 'In French', comparisons: 'Explore a comparison', contact: '/en/contact', methodHref: '/en/ressources/tools/methodology', profile: '/en/about/florent-greth', profileLabel: 'Florent Greth, Pennylane integration',
  },
  es: {
    eyebrow: 'Herramientas financieras desde la perspectiva del CFO', title: 'Herramientas financieras: opiniones y criterios de CFO', intro: '¿Qué software elegir para contabilidad, caja o gastos? Las fichas distinguen experiencia confirmada del gabinete y análisis documental. Examine ventajas, límites y coste total antes de decidir.', explore: 'Explorar herramientas por necesidad', stack: 'Preparar mis herramientas financieras', maturity: 'Empiece por su organización', maturityIntro: 'La madurez de los procesos importa más que un umbral automático de facturación.', stages: [
      ['Primera organización', 'Una base sencilla y datos fiables', 'Contabilidad, facturas, banca y justificantes. Defina quién controla los documentos y los permisos de pago antes de añadir software.', 'Cambiar cuando los documentos pendientes y las tareas repetidas impiden cerrar con regularidad.'],
      ['Actividad en crecimiento', 'Conectar caja, gastos y reporting', 'Añada previsiones actualizadas, aprobaciones e indicadores comunes. Pruebe las conexiones con operaciones reales.', 'Cambiar cuando las previsiones llegan tarde o cada informe requiere una nueva conciliación.'],
      ['Varias entidades o países', 'Definiciones y responsabilidades compartidas', 'ERP, tesorería de grupo y reporting requieren reglas de cierre, permisos y migración documentados. Presupueste también el mantenimiento de interfaces.', 'Cambiar cuando las sociedades no pueden producir datos comparables y trazables.'],
    ], signal: 'Cuándo revisar la elección', directory: 'Explore las fichas de herramientas', directoryIntro: 'Filtre las herramientas según sus necesidades y examine los perfiles adecuados, las limitaciones y los requisitos de implantación. Las fichas detalladas están actualmente en francés.', field: 'Pennylane: experiencia confirmada', fieldText: 'Iter utiliza Pennylane desde hace cuatro años, para aproximadamente el 50 % de sus clientes. Su punto fuerte para nosotros es centralizar la contabilidad y preparar datos contables limpios. Nuestra reserva es un reporting todavía limitado para algunas necesidades de gestión.', fieldLink: 'Leer nuestra opinión sobre Pennylane', method: 'Un método transparente', methodText: 'Distinguimos documentación del proveedor, criterios de selección y experiencia confirmada del gabinete. Los precios enlazan a sus fuentes; no inventamos puntuaciones ni resultados de clientes.', methodLink: 'Leer la metodología', french: 'En francés', comparisons: 'Profundizar en una comparación', contact: '/es/contact', methodHref: '/es/recursos/herramientas/metodologia', profile: '/es/quienes-somos/florent-greth', profileLabel: 'Florent Greth, integración de Pennylane',
  },
} satisfies Record<Locale, unknown>;
