import type { Locale } from '@/lib/i18n';
export const TOOL_METHODOLOGY = {
  fr: { title: 'Méthode des avis outils finance | Iter Advisors', h1: 'Comment nous construisons nos avis sur les outils finance', intro: 'Une fiche utile doit permettre de décider : quel besoin est couvert, pour quelle organisation, avec quelles limites et quel effort de mise en place. Notre méthode sépare les faits documentés, les critères de DAF et les retours d’usage confirmés.', sections: [
    ['Trois niveaux de preuve distincts', 'La documentation officielle décrit les fonctions et les conditions proposées par l’éditeur. L’analyse de DAF examine leur pertinence pour un processus financier. Le retour d’usage rapporte uniquement une expérience du cabinet effectivement confirmée. Un critère de sélection ou un protocole de démonstration ne constitue pas un résultat client.'],
    ['Ce que nous évaluons', 'Nous examinons le besoin métier, les profils adaptés, les situations à écarter, les données d’entrée, les droits d’accès, les interfaces et la possibilité de récupérer les données. Nous demandons des tests sur les exceptions : avoirs, paiements partiels, devises, corrections, départs de salariés ou opérations sur le capital, selon la catégorie.'],
    ['Prix : abonnement et coût du projet', 'Les fiches relient la tarification à une source éditeur et indiquent sa date de vérification. Un montant affiché ne couvre pas nécessairement les utilisateurs, les entités, les volumes, la reprise, les connecteurs, la formation et le support. Un devis daté à périmètre identique reste nécessaire ; nous ne présentons pas une ancienne grille comme un tarif actuel.'],
    ['Une attribution qui ne fabrique pas une validation', 'Le signataire éditorial est identifié par un lien vers son profil. Cette attribution n’affirme pas qu’il a personnellement testé toutes les versions du produit. Un relecteur, une certification, un verbatim signé ou un cas client ne sont ajoutés qu’après validation réelle. Nous ne publions pas de note sur cinq ni de classement fondé sur des résultats non documentés.'],
    ['Pennylane : expérience confirmée du cabinet', 'Au 3 octobre 2026, Iter confirme quatre ans d’utilisation de Pennylane et un usage pour environ 50 % de ses clients. Le point fort retenu est la centralisation comptable et une précomptabilité propre ; la réserve concerne le reporting pour certains besoins de pilotage. Ces éléments décrivent Iter, pas l’ensemble des utilisateurs ni la part de marché du produit.'],
    ['Transparence commerciale', 'Iter propose des prestations de direction financière et d’organisation des outils. Ces analyses ne sont donc pas celles d’un organisme indépendant de toute activité commerciale. La présence d’un logo ne signifie pas certification ou partenariat. Aucun lien de cette section ne comporte de paramètre d’affiliation. Tout éventuel accord avec un éditeur devra être déclaré sur la fiche concernée.'],
    ['Dates et corrections', 'La date de mise à jour change lors d’une modification substantielle de la fiche, sans être recalculée à chaque déploiement. La date tarifaire reste distincte. Pour signaler une erreur, indiquez le produit, la version, le pays, l’offre et la source à vérifier ; nous pouvons alors corriger le passage concerné.'],
  ], contact: 'Signaler une correction ou parler de votre projet', contactHref: '/contact', hub: '/ressources/outils', hubLabel: 'Explorer les avis outils' },
  en: { title: 'Finance software review method | Iter Advisors', h1: 'How we build our finance software reviews', intro: 'A useful guide helps you decide which need is covered, for which organisation, with what limits and implementation effort. Our method separates documented facts, CFO selection criteria and confirmed firm experience.', sections: [
    ['Three distinct levels of evidence', 'Official documentation describes publisher features and terms. CFO analysis examines their relevance to a finance process. An experience report covers only confirmed firm usage. A selection criterion or demonstration protocol is not a measured client result.'],
    ['What we examine', 'We assess business needs, suitable profiles, exclusions, input data, permissions, interfaces and data exports. We propose tests for exceptions such as credit notes, partial payments, currencies, corrections, employee departures or equity transactions, depending on the category.'],
    ['Pricing and project cost', 'Guides link to publisher pricing sources and state the verification date. Published prices may exclude users, entities, volumes, migration, connectors, training and support. A current quote for a consistent scope is required; an older price schedule is not presented as current.'],
    ['Attribution and validation', 'The editorial contributor links to an identifiable profile. This does not imply personal testing of every product version. A reviewer, certification, signed quotation or client case is added only after real validation. We do not publish undocumented numerical ratings or rankings.'],
    ['Pennylane: confirmed firm experience', 'As of 3 October 2026, Iter confirms four years of Pennylane use, for around 50% of its clients. The strength identified is centralised accounting and clean pre-accounting; the reservation concerns reporting for some management needs. These figures describe Iter, not the product’s market share.'],
    ['Commercial transparency', 'Iter provides fractional CFO and finance tooling services. These analyses do not come from an organisation with no commercial activity. A logo does not imply certification or partnership. Links in this section have no affiliate parameters. Any publisher agreement must be disclosed on the relevant guide.'],
    ['Dates and corrections', 'A guide’s update date changes following a substantive revision, not every deployment. Pricing verification dates remain separate. To report an error, specify the product, version, country, plan and source so the relevant passage can be checked.'],
  ], contact: 'Report a correction or discuss your project', contactHref: '/en/contact', hub: '/en/ressources/tools', hubLabel: 'Explore the software guides' },
  es: { title: 'Método de opiniones de software | Iter Advisors', h1: 'Cómo elaboramos las opiniones de herramientas financieras', intro: 'Una ficha útil ayuda a decidir qué necesidad cubre una solución, para qué organización y con qué límites y esfuerzo de implantación. Separamos hechos documentados, criterios de CFO y experiencia confirmada del gabinete.', sections: [
    ['Tres niveles de evidencia', 'La documentación oficial describe funciones y condiciones del proveedor. El análisis de CFO examina su pertinencia para un proceso financiero. La experiencia de uso solo recoge prácticas confirmadas del gabinete. Un criterio de selección o protocolo de demostración no constituye un resultado medido de cliente.'],
    ['Qué examinamos', 'Evaluamos necesidades, perfiles adecuados, exclusiones, datos de entrada, permisos, interfaces y exportaciones. Proponemos pruebas de excepciones: abonos, pagos parciales, divisas, correcciones, bajas de empleados u operaciones de capital, según la categoría.'],
    ['Precio y coste del proyecto', 'Las fichas enlazan a fuentes de precios del proveedor e indican la fecha de comprobación. Los precios publicados pueden excluir usuarios, entidades, volúmenes, migración, conectores, formación y soporte. Hace falta un presupuesto actual con el mismo alcance; una tarifa anterior no se presenta como vigente.'],
    ['Atribución y validación', 'El responsable editorial tiene un enlace a su perfil. Esta atribución no implica una prueba personal de todas las versiones. Solo añadimos un revisor, certificación, cita firmada o caso de cliente tras validación real. No publicamos notas numéricas ni clasificaciones sin documentación.'],
    ['Pennylane: experiencia confirmada', 'A 3 de octubre de 2026, Iter confirma cuatro años de uso de Pennylane para aproximadamente el 50 % de sus clientes. La ventaja identificada es centralizar la contabilidad y preparar datos limpios; la reserva se refiere al reporting para algunas necesidades de gestión. Estas cifras describen Iter, no la cuota de mercado del producto.'],
    ['Transparencia comercial', 'Iter ofrece servicios de CFO externo y organización de herramientas financieras. Estos análisis no proceden de una entidad sin actividad comercial. Un logo no implica certificación o alianza. Los enlaces de esta sección no contienen parámetros de afiliación. Cualquier acuerdo con un proveedor debe declararse en la ficha correspondiente.'],
    ['Fechas y correcciones', 'La fecha de actualización cambia con una revisión sustancial, no en cada despliegue. La comprobación de precios conserva su propia fecha. Para comunicar un error, indique producto, versión, país, plan y fuente para verificar el pasaje afectado.'],
  ], contact: 'Comunicar una corrección o hablar de su proyecto', contactHref: '/es/contact', hub: '/es/recursos/herramientas', hubLabel: 'Explorar las fichas de herramientas' },
} satisfies Record<Locale, unknown>;
export const METHODOLOGY_PATHS = { fr: '/ressources/outils/methodologie', en: '/en/ressources/tools/methodology', es: '/es/recursos/herramientas/metodologia' };
