import CopyPrompt from "./CopyPrompt";
export default function ReportingKit() {
  return <section>
    <h2 id="kit-reporting" className="scroll-mt-24">Essayez sur un reporting fictif, avec son corrigé</h2>
    <p>Ce kit pédagogique ne contient aucune donnée client. Il décrit un mois pour une entreprise fictive, en milliers d’euros, avec des charges positives. Le solde CA moins charges n’est pas un EBITDA comptable.</p>
    <p><a href="/downloads/kit-reporting-pme.zip" download className="font-semibold">Télécharger le kit complet (ZIP)</a> ou <a href="/downloads/reporting-pme-exercice.csv" download>ouvrir le fichier CSV</a>.</p>
    <ol><li>Ouvrez les données dans Excel ou votre tableur : séparateur point-virgule, encodage UTF-8. Vérifiez la période, l’entité, l’unité et l’unicité des identifiants.</li><li>Agrégez le chiffre d’affaires et les charges, puis calculez les écarts. Comparez avec le corrigé fourni.</li><li>Utilisez le prompt ci-dessous sur ce fichier fictif. Rejetez toute cause non présente dans les données.</li><li>Testez ensuite le fichier avec doublon : le contrôle doit identifier la ligne répétée avant de valider le total.</li></ol>
    <div className="prose-table-wrapper"><table><caption>Résultat attendu du fichier valide, en k€</caption><thead><tr><th scope="col">Indicateur</th><th scope="col">Budget</th><th scope="col">Réel</th><th scope="col">Écart</th></tr></thead><tbody><tr><th scope="row">Chiffre d’affaires</th><td>200</td><td>180</td><td>−20 (−10 %)</td></tr><tr><th scope="row">Charges</th><td>150</td><td>155</td><td>+5 (+3,33 %)</td></tr><tr><th scope="row">Solde simplifié</th><td>50</td><td>25</td><td>−25 (−50 %)</td></tr></tbody></table></div>
    <CopyPrompt text="Analyse ce reporting fictif en k€. Vérifie les identifiants dupliqués, les périodes, les unités et les champs vides avant tout calcul. En cas d’anomalie, indique-la et suspends la validation des totaux. Sinon, calcule le CA, les charges et le solde simplifié, puis leurs écarts au budget. Montre les opérations ou le code utilisé. Rédige un commentaire de 120 mots maximum, en séparant faits, hypothèses et questions. N’invente aucune cause. Un pourcentage avec budget nul est non calculable." />
    <p><strong>Commentaire de référence :</strong> le CA est inférieur au budget de 20 k€ et les charges le dépassent de 5 k€. Le solde simplifié baisse donc de 25 k€. Les données ne permettent pas d’attribuer ces écarts à un prix, un volume ou un recrutement : ces causes doivent être vérifiées auprès des responsables.</p>
    <p>La réussite de cet exercice ne valide pas un déploiement sur vos comptes. Le <a href="/ressources/ia-finance/feuille-de-route-90-jours">protocole de pilote</a> décrit les contrôles à organiser avec votre équipe.</p>
  </section>;
}
