import type { Locale } from "@/lib/i18n";
const copy = {
  fr: { title: "Un livrable, un responsable, une décision", intro: "Exemples à sélectionner au cadrage. La proposition précise les livrables, les données à fournir et les validations attendues.", headers: ["Support de travail", "Ce qu’Iter prépare", "Ce que votre équipe valide"], finance: [["Prévision de trésorerie", "Flux, hypothèses, écarts et scénarios documentés.", "Dates d’encaissement, échéances et décisions de financement."], ["Reporting mensuel", "Indicateurs définis, sources rapprochées et questions à arbitrer.", "Qualité des données, explication métier des écarts et actions retenues."], ["Budget", "Hypothèses, scénarios et suivi du réalisé.", "Priorités, recrutements et engagements de dépenses."]], hr: [["Feuille de route RH", "Priorités, calendrier et coordination des intervenants.", "Décisions d’employeur et ressources nécessaires."], ["Recrutement et intégration", "Fiches de poste, étapes et supports de suivi convenus.", "Choix des candidats, contrats et responsabilités des managers."], ["Suivi de la paie", "Calendrier, collecte des variables et coordination du prestataire.", "Données transmises, validation des bulletins par le responsable habilité."]], note: "La production comptable, juridique ou de paie relève des intervenants désignés dans le contrat." },
  en: { title: "A deliverable, an owner, a decision", intro: "Examples to select during scoping. The proposal specifies deliverables, required inputs and approvals.", headers: ["Working document", "What Iter prepares", "What your team validates"], finance: [["Cash forecast", "Documented cash flows, assumptions, variances and scenarios.", "Receipt dates, due dates and financing decisions."], ["Monthly reporting", "Defined indicators, reconciled sources and decisions to discuss.", "Data quality, business explanations of variances and agreed actions."], ["Budget", "Assumptions, scenarios and actuals monitoring.", "Priorities, hiring and spending commitments."]], hr: [["HR roadmap", "Priorities, schedule and coordination of contributors.", "Employer decisions and required resources."], ["Hiring and onboarding", "Job descriptions, steps and agreed tracking documents.", "Candidate selection, contracts and managers’ responsibilities."], ["Payroll oversight", "Schedule, collection of variable data and provider coordination.", "Submitted inputs and payslip approval by the authorised owner."]], note: "Accounting, legal or payroll production belongs to the parties designated in the contract." },
  es: { title: "Un entregable, un responsable, una decisión", intro: "Ejemplos para seleccionar al definir el alcance. La propuesta precisa entregables, datos necesarios y validaciones.", headers: ["Documento de trabajo", "Qué prepara Iter", "Qué valida su equipo"], finance: [["Previsión de tesorería", "Flujos, hipótesis, desviaciones y escenarios documentados.", "Fechas de cobro, vencimientos y decisiones de financiación."], ["Reporting mensual", "Indicadores definidos, fuentes conciliadas y decisiones que examinar.", "Calidad de datos, explicación de desviaciones y acciones acordadas."], ["Presupuesto", "Hipótesis, escenarios y seguimiento del realizado.", "Prioridades, contratación y compromisos de gasto."]], hr: [["Hoja de ruta de RRHH", "Prioridades, calendario y coordinación de los participantes.", "Decisiones como empleador y recursos necesarios."], ["Selección e incorporación", "Fichas de puesto, etapas y documentos de seguimiento acordados.", "Selección de candidatos, contratos y responsabilidades de los managers."], ["Seguimiento de nómina", "Calendario, recogida de variables y coordinación del proveedor.", "Datos transmitidos y aprobación de nóminas por el responsable autorizado."]], note: "La producción contable, jurídica o de nómina corresponde a los participantes designados en el contrato." },
};
export default function ScopeResponsibilities({ locale, kind }: { locale: Locale; kind: "finance" | "hr" }) {
  const t = copy[locale];
  return <div className="mt-8">
    <h3 className="font-heading text-xl font-semibold mb-3">{t.title}</h3><p className="text-muted-foreground mb-4">{t.intro}</p>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm border-collapse"><caption className="sr-only">{t.title}</caption><thead><tr>{t.headers.map(h => <th key={h} scope="col" className="border-b p-3 font-semibold">{h}</th>)}</tr></thead><tbody>{t[kind].map(row => <tr key={row[0]}><th scope="row" className="border-b p-3 font-semibold align-top">{row[0]}</th>{row.slice(1).map(cell => <td key={cell} className="border-b p-3 align-top min-w-44">{cell}</td>)}</tr>)}</tbody></table></div>
    <p className="mt-3 text-sm text-muted-foreground">{t.note}</p>
  </div>;
}
