/**
 * Auto-generated by `scripts/generate-blog-covers.ts` — do not edit by hand.
 * Maps each blog article slug to its editorial cover SVG and the alt
 * text consumed by <Image alt={…}>.
 *
 * Re-run `npx tsx scripts/generate-blog-covers.ts` after changing
 * titles / subtitles / categories in that script.
 */

export interface BlogCover {
  cover: string;
  alt: string;
}

export const BLOG_COVERS: Record<string, BlogCover> = {
  "impot-revenu-espagne": { cover: "/images/blog/covers/impot-revenu-espagne.svg", alt: "Couverture editoriale Iter Advisors — Impot sur le revenu en Espagne, guide complet 2026 pour expatries et entreprises" },
  "externaliser-comptabilite-guide": { cover: "/images/blog/covers/externaliser-comptabilite-guide.svg", alt: "Couverture editoriale Iter Advisors — Externaliser sa comptabilite, guide pratique pour startups et PME" },
  "quand-embaucher-daf-externalise-5-signes": { cover: "/images/blog/covers/quand-embaucher-daf-externalise-5-signes.svg", alt: "Couverture editoriale Iter Advisors — Quand embaucher un DAF externalise, 5 signaux qui ne trompent pas" },
  "daf-externalise-barcelone-guide-startups-espagnoles": { cover: "/images/blog/covers/daf-externalise-barcelone-guide-startups-espagnoles.svg", alt: "Couverture editoriale Iter Advisors — DAF externalise a Barcelone, le guide pour les startups espagnoles" },
  "cout-daf-externalise-2026-tarifs-par-mission": { cover: "/images/blog/covers/cout-daf-externalise-2026-tarifs-par-mission.svg", alt: "Couverture editoriale Iter Advisors — Cout d'un DAF externalise en 2026, tarifs detailles par mission" },
  "daf-externalise-vs-expert-comptable": { cover: "/images/blog/covers/daf-externalise-vs-expert-comptable.svg", alt: "Couverture editoriale Iter Advisors — DAF externalise vs expert-comptable, quelle est la vraie difference" },
  "pennylane-vs-sage-comparatif-40-deploiements": { cover: "/images/blog/covers/pennylane-vs-sage-comparatif-40-deploiements.svg", alt: "Couverture editoriale Iter Advisors — Pennylane vs Sage, comparatif apres 40 deploiements" },
  "agicap-vs-fygr-outil-tresorerie": { cover: "/images/blog/covers/agicap-vs-fygr-outil-tresorerie.svg", alt: "Couverture editoriale Iter Advisors — Agicap vs Fygr, quel outil de tresorerie choisir" },
  "stack-financier-saas-series-a": { cover: "/images/blog/covers/stack-financier-saas-series-a.svg", alt: "Couverture editoriale Iter Advisors — Le stack financier ideal pour une SaaS Series A en 5 couches" },
  "data-room-checklist-levee-de-fonds": { cover: "/images/blog/covers/data-room-checklist-levee-de-fonds.svg", alt: "Couverture editoriale Iter Advisors — Checklist data room levee de fonds, tout ce que les investisseurs attendent" },
  "term-sheet-negocier-clauses-cles": { cover: "/images/blog/covers/term-sheet-negocier-clauses-cles.svg", alt: "Couverture editoriale Iter Advisors — Negocier sa term sheet, les clauses cles a defendre" },
  "due-diligence-financiere-investisseurs": { cover: "/images/blog/covers/due-diligence-financiere-investisseurs.svg", alt: "Couverture editoriale Iter Advisors — Due diligence financiere, ce que les investisseurs verifient vraiment" },
  "reduire-bfr-7-leviers-actionnables": { cover: "/images/blog/covers/reduire-bfr-7-leviers-actionnables.svg", alt: "Couverture editoriale Iter Advisors — Reduire son BFR, 7 leviers actionnables" },
  "cash-burn-calculer-runway-anticiper-levee": { cover: "/images/blog/covers/cash-burn-calculer-runway-anticiper-levee.svg", alt: "Couverture editoriale Iter Advisors — Cash burn et runway, quand lever des fonds avant qu'il ne soit trop tard" },
  "tableau-de-bord-financier-startup-12-kpis": { cover: "/images/blog/covers/tableau-de-bord-financier-startup-12-kpis.svg", alt: "Couverture editoriale Iter Advisors — Tableau de bord financier startup, les 12 KPIs a suivre" },
  "drh-externalise-quand-et-pourquoi": { cover: "/images/blog/covers/drh-externalise-quand-et-pourquoi.svg", alt: "Couverture editoriale Iter Advisors — Le DRH externalise, quand y faire appel et pourquoi ca paye" },
  "payfit-vs-silae-comparatif-pme": { cover: "/images/blog/covers/payfit-vs-silae-comparatif-pme.svg", alt: "Couverture editoriale Iter Advisors — PayFit vs Silae, comparatif pour PME en croissance" },
  "flux-de-tresorerie": { cover: "/images/blog/covers/flux-de-tresorerie.svg", alt: "Couverture editoriale Iter Advisors — Flux de tresorerie, definition, importance et indicateurs cles" },
  "cas-etude-happy-scribe": { cover: "/images/blog/covers/cas-etude-happy-scribe.svg", alt: "Couverture editoriale Iter Advisors — Cas client Happy Scribe, comment une scale-up a structure sa finance" },
  "externalisation-comptable": { cover: "/images/blog/covers/externalisation-comptable.svg", alt: "Couverture editoriale Iter Advisors — Externalisation comptable en pratique, guide pragmatique pour dirigeants" },
  "cout-daf-externalise-tarifs-prix-2026": { cover: "/images/blog/covers/cout-daf-externalise-tarifs-prix-2026.svg", alt: "Couverture editoriale Iter Advisors — Tarifs DAF externalise 2026, grille de prix, TJM et calcul du ROI" },
  "daf-externalise-vs-daf-salarie": { cover: "/images/blog/covers/daf-externalise-vs-daf-salarie.svg", alt: "Couverture editoriale Iter Advisors — DAF externalise vs DAF salarie, quel modele pour quel stade" },
  "checklist-due-diligence-levee-de-fonds": { cover: "/images/blog/covers/checklist-due-diligence-levee-de-fonds.svg", alt: "Couverture editoriale Iter Advisors — Checklist due diligence financiere pour levee de fonds" },
  "daf-drh-externalises-synergie": { cover: "/images/blog/covers/daf-drh-externalises-synergie.svg", alt: "Couverture editoriale Iter Advisors — DAF et DRH externalises, pourquoi le duo change tout" },
  "la-modernisation-du-role-de-cfo": { cover: "/images/blog/covers/la-modernisation-du-role-de-cfo.svg", alt: "Couverture editoriale Iter Advisors — Le CFO moderne, comment le metier a ete reecrit" },
  "les-10-outils-pour-cfos-startup": { cover: "/images/blog/covers/les-10-outils-pour-cfos-startup.svg", alt: "Couverture editoriale Iter Advisors — 10 outils essentiels pour CFO startup, la shortlist du praticien" },
  "daf-externalise-guide": { cover: "/images/blog/covers/daf-externalise-guide.svg", alt: "Couverture editoriale Iter Advisors — Le guide complet du DAF externalise, tarifs et cas client" },
  "essentiels-outils-tech-finance": { cover: "/images/blog/covers/essentiels-outils-tech-finance.svg", alt: "Couverture editoriale Iter Advisors — Les outils tech essentiels pour la finance, la stack 2026" },
  "ia-et-automatisation-des-taches-repetitives": { cover: "/images/blog/covers/ia-et-automatisation-des-taches-repetitives.svg", alt: "Couverture editoriale Iter Advisors — IA et automatisation finance, repenser les taches repetitives" },
  "levee-de-fonds-guide": { cover: "/images/blog/covers/levee-de-fonds-guide.svg", alt: "Couverture editoriale Iter Advisors — Lever des fonds, le guide complet pour fondateurs" },
  "organiser-sa-direction-financiere": { cover: "/images/blog/covers/organiser-sa-direction-financiere.svg", alt: "Couverture editoriale Iter Advisors — Organiser sa direction financiere, le manuel de structuration" },
  "regimes-fiscaux-france-vs-espagne": { cover: "/images/blog/covers/regimes-fiscaux-france-vs-espagne.svg", alt: "Couverture editoriale Iter Advisors — Regimes fiscaux France vs Espagne, le comparatif pour dirigeants" },
  "daf-externalise-vs-daf-interimaire": { cover: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé ou DAF intérimaire : comparatif 2026" },
  "daf-externalise-startup": { cover: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé pour startups en croissance" },
  "loi-beckham-espagne-conditions-eligibilite": { cover: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1200&q=80", alt: "Conditions d'éligibilité à la loi Beckham en Espagne" },
  "loi-beckham-economie-impot-simulation": { cover: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=1200&q=80", alt: "Simulation de l'économie d'impôt avec la loi Beckham" },
  "daf-part-time-tarifs-missions-2026": { cover: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=1200&q=80", alt: "Tarifs d'un DAF à temps partagé en 2026" },
  "cfo-externe-role-missions-2026": { cover: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", alt: "CFO externe en mission dans une PME" },
  "fractional-cfo-cost-services-2026": { cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80", alt: "Fractional CFO working with a startup board" },
  "cfo-externo-pymes-precio-2026": { cover: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80", alt: "CFO externo para pymes en Barcelona" },
};

export function getBlogCover(slug: string): BlogCover | undefined {
  return BLOG_COVERS[slug];
}
