/**
 * Auto-generated by `scripts/generate-blog-covers.ts` — do not edit by hand.
 * Maps each blog article slug to its editorial cover SVG and the alt
 * text consumed by <Image alt={…}>.
 *
 * Re-run `npx tsx scripts/generate-blog-covers.ts` after changing
 * titles / subtitles / categories in that script.
 */

export interface BlogCover {
  cover: string;
  alt: string;
}

export const BLOG_COVERS: Record<string, BlogCover> = {
  // ── Articles mis à jour avec photos réelles (Unsplash) ──────────────────
  "flux-de-tresorerie": { cover: "https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=1200&q=80", alt: "Flux de trésorerie : définition, calcul et pilotage pour PME" },
  "externalisation-comptable": { cover: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80", alt: "Externalisation comptable : le guide pratique pour PME et startups" },
  "impot-revenu-espagne": { cover: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80", alt: "Impôt sur le revenu en Espagne (IRPF) : barème 2026" },
  "bareme-irpf-espagne-2026": { cover: "https://images.unsplash.com/photo-1524813686514-a57563d77965?auto=format&fit=crop&w=1200&q=80", alt: "Barème IRPF Espagne 2026 : tranches, taux et calcul de l'impôt sur le revenu" },
  "cout-daf-externalise-tarifs-prix-2026": { cover: "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=1200&q=80", alt: "Combien coûte un DAF externalisé en 2026 : tarifs et grille de prix" },
  "daf-externalise-vs-daf-salarie": { cover: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé ou DAF salarié : comparatif coûts et avantages" },
  "loi-beckham-espagne-conditions-eligibilite": { cover: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1200&q=80", alt: "Loi Beckham en Espagne : conditions d'éligibilité du régime impatrié" },
  "double-imposition-france-espagne": { cover: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1200&q=80", alt: "Double imposition France-Espagne : la convention fiscale expliquée" },
  "double-imposition-france-espagne-convention": { cover: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1200&q=80", alt: "Convention fiscale France-Espagne : éviter la double imposition en 2026" },
  "modelo-720-declaration-biens-etranger": { cover: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=1200&q=80", alt: "Modelo 720 : déclarer ses biens à l'étranger en Espagne" },
  "payfit-vs-silae-comparatif-pme": { cover: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80", alt: "PayFit vs Silae : comparatif paie et RH pour PME 2026" },
  "pennylane-vs-sage-comparatif-40-deploiements": { cover: "https://images.unsplash.com/photo-1542744094-24638eff58bb?auto=format&fit=crop&w=1200&q=80", alt: "Pennylane vs Sage : comparatif terrain après 40 déploiements" },
  "checklist-due-diligence-levee-de-fonds": { cover: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80", alt: "Due diligence financière : la checklist pour préparer sa levée" },
  "daf-externalise-vs-expert-comptable": { cover: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé ou expert-comptable : quelle différence ?" },
  "drh-externalise-quand-et-pourquoi": { cover: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80", alt: "DRH externalisé : quand et pourquoi y recourir" },
  "daf-drh-externalises-synergie": { cover: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80", alt: "DAF et DRH externalisés : pourquoi combiner les deux fonctions" },
  "daf-externalise-barcelone-guide-startups-espagnoles": { cover: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé à Barcelone : le guide pour startups françaises" },
  "quand-embaucher-daf-externalise-5-signes": { cover: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=80", alt: "Quand embaucher un DAF externalisé : les 5 signes" },
  "stack-financier-saas-series-a": { cover: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80", alt: "Le stack financier idéal pour une SaaS en Series A" },
  "tableau-de-bord-financier-startup-12-kpis": { cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", alt: "Tableau de bord financier startup : les 12 KPI à suivre" },
  "cas-etude-happy-scribe": { cover: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80", alt: "Cas client Happy Scribe : structurer les finances d'une scale-up" },
  "cash-burn-calculer-runway-anticiper-levee": { cover: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80", alt: "Cash burn : calculer sa runway et anticiper sa levée de fonds" },
  "reduire-bfr-7-leviers-actionnables": { cover: "https://images.unsplash.com/photo-1579532537598-459ecdaf39cc?auto=format&fit=crop&w=1200&q=80", alt: "Réduire son BFR : 7 leviers actionnables pour libérer du cash" },
  "externaliser-comptabilite-guide": { cover: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80", alt: "Externaliser sa comptabilité : le guide complet" },
  "cout-daf-externalise-2026-tarifs-par-mission": { cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1200&q=80", alt: "Coût d'un DAF externalisé : tarifs par mission en 2026" },
  "agicap-vs-fygr-outil-tresorerie": { cover: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80", alt: "Agicap ou Fygr : quel outil de trésorerie choisir" },
  "data-room-checklist-levee-de-fonds": { cover: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", alt: "Data room : la checklist complète pour votre levée de fonds" },
  "term-sheet-negocier-clauses-cles": { cover: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80", alt: "Term sheet : comment négocier les clauses clés" },
  "due-diligence-financiere-investisseurs": { cover: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=80", alt: "Due diligence financière : ce que les investisseurs vérifient" },
  // ── Articles nouveaux (session juillet 2026) ─────────────────────────────
  "daf-externalise-vs-daf-interimaire": { cover: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé ou DAF intérimaire : comparatif 2026" },
  "daf-externalise-startup": { cover: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80", alt: "DAF externalisé pour startups en croissance" },
  "loi-beckham-economie-impot-simulation": { cover: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=1200&q=80", alt: "Simulation de l'économie d'impôt avec la loi Beckham" },
  "daf-part-time-tarifs-missions-2026": { cover: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=1200&q=80", alt: "Tarifs d'un DAF à temps partagé en 2026" },
  "cfo-externe-role-missions-2026": { cover: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", alt: "CFO externe en mission dans une PME" },
  "fractional-cfo-cost-services-2026": { cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80", alt: "Fractional CFO working with a startup board" },
  "cfo-externo-pymes-precio-2026": { cover: "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?auto=format&fit=crop&w=1200&q=80", alt: "CFO externo para pymes: funciones y precio en 2026" },
  "ia-finance-automatisation-direction-financiere": { cover: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80", alt: "Automatisation et IA pour la fonction finance" },
  // ── Articles tuile pastel conservée (carte bleue Iter Advisors) ──────────
  "la-modernisation-du-role-de-cfo": { cover: "/images/blog/covers/la-modernisation-du-role-de-cfo.svg", alt: "Couverture editoriale Iter Advisors — Le CFO moderne, comment le metier a ete reecrit" },
  "les-10-outils-pour-cfos-startup": { cover: "/images/blog/covers/les-10-outils-pour-cfos-startup.svg", alt: "Couverture editoriale Iter Advisors — 10 outils essentiels pour CFO startup, la shortlist du praticien" },
  "daf-externalise-guide": { cover: "/images/blog/covers/daf-externalise-guide.svg", alt: "Couverture editoriale Iter Advisors — Le guide complet du DAF externalise, tarifs et cas client" },
  "essentiels-outils-tech-finance": { cover: "/images/blog/covers/essentiels-outils-tech-finance.svg", alt: "Couverture editoriale Iter Advisors — Les outils tech essentiels pour la finance, la stack 2026" },
  "ia-et-automatisation-des-taches-repetitives": { cover: "/images/blog/covers/ia-et-automatisation-des-taches-repetitives.svg", alt: "Couverture editoriale Iter Advisors — IA et automatisation finance, repenser les taches repetitives" },
  "levee-de-fonds-guide": { cover: "/images/blog/covers/levee-de-fonds-guide.svg", alt: "Couverture editoriale Iter Advisors — Lever des fonds, le guide complet pour fondateurs" },
  "organiser-sa-direction-financiere": { cover: "/images/blog/covers/organiser-sa-direction-financiere.svg", alt: "Couverture editoriale Iter Advisors — Organiser sa direction financiere, le manuel de structuration" },
  "regimes-fiscaux-france-vs-espagne": { cover: "/images/blog/covers/regimes-fiscaux-france-vs-espagne.svg", alt: "Couverture editoriale Iter Advisors — Regimes fiscaux France vs Espagne, le comparatif pour dirigeants" },
};

export function getBlogCover(slug: string): BlogCover | undefined {
  return BLOG_COVERS[slug];
}
