/**
 * Helper that assembles the blog listing from the static
 * `lib/content/blog-posts.ts` source (instead of Strapi). It returns
 * pseudo-`StrapiBlogArticle` objects so `BlogListingPage` can keep its
 * existing rendering path.
 *
 * Resolves the cover image by best-effort filename matching against
 * `public/images/blog/` — if no specific image exists for a slug we
 * fall back to a generic placeholder.
 */

import { blogPosts } from "@/lib/content/blog-posts";
import { BLOG_COVERS } from "@/lib/blog-covers";
import type { Locale } from "@/lib/i18n";
import type { StrapiBlogArticle, StrapiMedia } from "@/lib/strapi";

/**
 * Editorial covers (1200×900 SVG, magazine style) generated by
 * `scripts/generate-blog-covers.ts` and committed under
 * `public/images/blog/covers/`. The slug→{cover,alt} map lives in
 * `lib/blog-covers.ts` (auto-generated, do not edit by hand).
 *
 * Legacy `.webp` covers under `public/images/blog/` are kept as a
 * fallback for slugs not yet listed in BLOG_COVERS.
 */
const LEGACY_COVER_BY_SLUG: Record<string, string> = {
  "10-outils-cfos-startup": "/images/blog/10-outils-cfos-startup.webp",
  "daf-externalise-guide": "/images/blog/daf-externalise.webp",
  "essentiels-outils-tech-finance": "/images/blog/essentiels-outils-tech-finance.webp",
  "ia-et-automatisation-des-taches-repetitives":
    "/images/blog/ia-et-automatisation-des-taches-repetitives.webp",
  "ia-et-automatisation-des-taches-repetitives-du-departement-finance":
    "/images/blog/ia-automatisation-finance.webp",
  "levee-de-fonds-guide": "/images/blog/levee-de-fonds.webp",
  "organiser-sa-direction-financiere": "/images/blog/organiser-sa-direction-financiere.webp",
};

const DEFAULT_COVER = "/images/blog/placeholder.webp";

function coverFor(slug: string): string {
  return BLOG_COVERS[slug]?.cover ?? LEGACY_COVER_BY_SLUG[slug] ?? DEFAULT_COVER;
}

function altFor(slug: string, fallbackTitle: string): string {
  return BLOG_COVERS[slug]?.alt ?? fallbackTitle;
}

function buildMedia(slug: string, title: string): StrapiMedia {
  return {
    id: 0,
    url: coverFor(slug),
    alternativeText: altFor(slug, title),
  } as unknown as StrapiMedia;
}

/**
 * Returns every static article available for `locale`, sorted newest
 * first. Shape matches `StrapiBlogArticle[]` so callers can feed it to
 * `BlogListingPage` as the `articles` prop with no other changes.
 */
export function getStaticBlogListing(locale: Locale): StrapiBlogArticle[] {
  const entries = Object.entries(blogPosts[locale] ?? {});
  const articles: StrapiBlogArticle[] = entries.map(([slug, post]) => {
    const description = post.meta?.description ?? "";
    const publishedDate = post.publishedDate ?? "";
    return {
      id: 0,
      documentId: slug,
      slug,
      title: post.h1 ?? slug,
      // BlogListingPage doesn't use these, but the type requires them.
      content: [],
      excerpt: description,
      featuredImage: buildMedia(slug, post.h1 ?? slug),
      publishedDate,
      tableOfContents: false,
      category: post.category ?? "",
    } as StrapiBlogArticle;
  });

  // Newest first when a publishedDate is present; otherwise stable order.
  articles.sort((a, b) => {
    if (!a.publishedDate && !b.publishedDate) return 0;
    if (!a.publishedDate) return 1;
    if (!b.publishedDate) return -1;
    return b.publishedDate.localeCompare(a.publishedDate);
  });

  return articles;
}
