import { StrapiGlossaryTerm } from "./strapi";
import { Locale } from "./i18n";

const glossaryFr: StrapiGlossaryTerm[] = [
  {
    id: 1,
    documentId: "chiffre-affaires",
    title: "Chiffre d'affaires",
    slug: "chiffre-d-affaires",
    definition: "Le chiffre d'affaires correspond au total des ventes réalisées par une entreprise sur une période donnée. Il mesure l'activité commerciale brute, avant déduction des coûts et des charges. Un directeur financier s'en sert pour suivre la croissance, fixer des objectifs et situer le niveau d'activité.",
    content: [],
  },
  {
    id: 2,
    documentId: "marge-brute",
    title: "Marge brute",
    slug: "marge-brute",
    definition: "La marge brute représente ce qu'il reste après avoir retiré les coûts directement liés à la vente ou à la production. Elle permet de voir si l'offre vendue crée assez de valeur avant les frais de structure.",
    content: [],
  },
  {
    id: 3,
    documentId: "ebitda",
    title: "EBITDA",
    slug: "ebitda",
    definition: "L'EBITDA mesure la performance opérationnelle avant les intérêts, les impôts et les amortissements. Il isole la capacité de l'activité à générer du résultat à partir de son fonctionnement courant.",
    content: [],
  },
  {
    id: 4,
    documentId: "resultat-net",
    title: "Résultat net",
    slug: "resultat-net",
    definition: "Le résultat net est le bénéfice ou la perte finale après toutes les charges, y compris les intérêts et l'impôt. C'est le niveau de performance qui reste en bas du compte de résultat.",
    content: [],
  },
  {
    id: 5,
    documentId: "cash-flow",
    title: "Cash-flow",
    slug: "cash-flow",
    definition: "Le cash-flow décrit les flux d'argent qui entrent et sortent de l'entreprise. Il montre si l'activité produit réellement du cash, au-delà des écritures comptables.",
    content: [],
  },
  {
    id: 6,
    documentId: "tresorerie",
    title: "Trésorerie",
    slug: "tresorerie",
    definition: "La trésorerie correspond à l'argent disponible immédiatement sur les comptes et les équivalents de trésorerie. Elle permet de payer les dépenses courantes sans délai.",
    content: [],
  },
  {
    id: 7,
    documentId: "besoin-fonds-roulement",
    title: "Besoin en fonds de roulement (BFR)",
    slug: "besoin-en-fonds-de-roulement",
    definition: "Le BFR représente l'argent nécessaire pour financer le décalage entre les encaissements clients et les décaissements fournisseurs, stocks inclus. Une forte croissance peut consommer beaucoup de cash si le BFR se dégrade.",
    content: [],
  },
  {
    id: 8,
    documentId: "fonds-roulement",
    title: "Fonds de roulement (FR)",
    slug: "fonds-de-roulement",
    definition: "Le fonds de roulement correspond aux ressources stables disponibles pour financer l'activité. L'équilibre financier classique consiste à couvrir le BFR avec un fonds de roulement suffisant.",
    content: [],
  },
  {
    id: 9,
    documentId: "point-mort",
    title: "Point mort",
    slug: "point-mort",
    definition: "Le point mort est le niveau de chiffre d'affaires à partir duquel l'entreprise couvre l'ensemble de ses coûts. En dessous, elle perd de l'argent. Au-dessus, elle commence à créer du résultat.",
    content: [],
  },
  {
    id: 10,
    documentId: "burn-rate",
    title: "Burn rate",
    slug: "burn-rate",
    definition: "Le burn rate mesure la vitesse à laquelle une entreprise consomme sa trésorerie. Il est très utilisé dans les startups ou les sociétés en phase d'investissement.",
    content: [],
  },
  {
    id: 11,
    documentId: "runway",
    title: "Runway",
    slug: "runway",
    definition: "Le runway correspond au nombre de mois pendant lesquels l'entreprise peut continuer à fonctionner avec sa trésorerie actuelle. Il dépend directement du burn rate.",
    content: [],
  },
  {
    id: 12,
    documentId: "budget",
    title: "Budget",
    slug: "budget",
    definition: "Le budget est la projection des revenus, des coûts et des investissements pour une période future. Il fixe un cadre de décision et une trajectoire attendue.",
    content: [],
  },
  {
    id: 13,
    documentId: "forecast",
    title: "Forecast",
    slug: "forecast",
    definition: "Le forecast est une révision du budget à partir des données réelles les plus récentes. Il donne une vision plus crédible de la trajectoire de fin d'année.",
    content: [],
  },
  {
    id: 14,
    documentId: "compte-resultat",
    title: "Compte de résultat (P&L)",
    slug: "compte-de-resultat",
    definition: "Le compte de résultat présente les revenus et les charges sur une période donnée pour expliquer comment se forme le résultat. Il raconte la performance économique de l'entreprise.",
    content: [],
  },
  {
    id: 15,
    documentId: "bilan",
    title: "Bilan",
    slug: "bilan",
    definition: "Le bilan est une photographie du patrimoine de l'entreprise à une date donnée. Il montre ce que l'entreprise possède à l'actif et ce qu'elle doit au passif.",
    content: [],
  },
  {
    id: 16,
    documentId: "capex",
    title: "CapEx",
    slug: "capex",
    definition: "Les CapEx sont les dépenses d'investissement destinées à créer de la valeur sur plusieurs années. Elles concernent par exemple des machines, des logiciels structurants ou des équipements.",
    content: [],
  },
  {
    id: 17,
    documentId: "opex",
    title: "OpEx",
    slug: "opex",
    definition: "Les OpEx sont les dépenses nécessaires au fonctionnement courant de l'entreprise. On y trouve par exemple les salaires, loyers, abonnements ou dépenses marketing récurrentes.",
    content: [],
  },
  {
    id: 18,
    documentId: "roi",
    title: "ROI",
    slug: "roi",
    definition: "Le ROI mesure le gain obtenu par rapport au coût d'un investissement. Il sert à savoir si l'argent engagé produit suffisamment de valeur.",
    content: [],
  },
  {
    id: 19,
    documentId: "dette",
    title: "Dette",
    slug: "dette",
    definition: "La dette correspond aux financements que l'entreprise devra rembourser selon un calendrier et des conditions définies. Elle permet de financer la croissance sans ouvrir le capital.",
    content: [],
  },
  {
    id: 20,
    documentId: "equity",
    title: "Equity",
    slug: "equity",
    definition: "L'equity représente les fonds apportés ou laissés dans l'entreprise par les actionnaires. Il constitue la base de propriété et de solidité financière.",
    content: [],
  },
  {
    id: 21,
    documentId: "dilution",
    title: "Dilution",
    slug: "dilution",
    definition: "La dilution est la baisse du pourcentage de détention d'un actionnaire après une émission de nouvelles actions. Elle ne signifie pas forcément une perte de valeur absolue, mais une part plus petite du capital.",
    content: [],
  },
  {
    id: 22,
    documentId: "valorisation",
    title: "Valorisation",
    slug: "valorisation",
    definition: "La valorisation est l'estimation de la valeur de l'entreprise à un moment donné. Elle sert de base dans une levée de fonds, une cession ou certaines négociations stratégiques.",
    content: [],
  },
  {
    id: 23,
    documentId: "ltv",
    title: "LTV",
    slug: "ltv",
    definition: "La LTV mesure le revenu ou la marge générée par un client sur toute la durée de la relation. Elle aide à comprendre combien vaut réellement un client dans le temps.",
    content: [],
  },
  {
    id: 24,
    documentId: "cac",
    title: "CAC",
    slug: "cac",
    definition: "Le CAC correspond au coût nécessaire pour gagner un nouveau client. Il inclut généralement les dépenses marketing et commerciales liées à l'acquisition.",
    content: [],
  },
  {
    id: 25,
    documentId: "free-cash-flow",
    title: "Free cash-flow",
    slug: "free-cash-flow",
    definition: "Le free cash-flow est le cash réellement disponible après les dépenses nécessaires au fonctionnement et aux investissements. Il montre la capacité de l'entreprise à générer du cash librement utilisable.",
    content: [],
  },
  {
    id: 26,
    documentId: "nav",
    title: "Valeur nette d'inventaire (NAV)",
    slug: "valeur-nette-d-inventaire",
    definition: "La NAV correspond à la valeur des actifs moins les dettes. Elle est souvent utilisée pour apprécier la valeur d'une holding, d'un fonds ou d'une société.",
    content: [],
  },
  {
    id: 27,
    documentId: "impot-societes",
    title: "Impôt sur les sociétés (IS)",
    slug: "impot-sur-les-societes",
    definition: "L'impôt sur les sociétés est un impôt annuel qui porte sur les bénéfices réalisés par les sociétés et autres personnes morales concernées.",
    content: [],
  },
  {
    id: 28,
    documentId: "resultat-fiscal",
    title: "Résultat fiscal",
    slug: "resultat-fiscal",
    definition: "Le résultat fiscal est la base de calcul de l'impôt, obtenue à partir du résultat comptable après retraitements prévus par la loi. Il peut donc être différent du résultat affiché dans les comptes.",
    content: [],
  },
  {
    id: 29,
    documentId: "tva",
    title: "TVA",
    slug: "tva",
    definition: "La TVA est un impôt indirect supporté par le consommateur et collecté par l'entreprise pour le compte de l'État. L'entreprise facture la TVA à ses clients puis reverse la différence.",
    content: [],
  },
  {
    id: 30,
    documentId: "amortissement",
    title: "Amortissement",
    slug: "amortissement",
    definition: "L'amortissement répartit le coût d'un actif sur sa durée d'utilisation estimée. Il traduit comptablement la consommation progressive de la valeur d'un investissement.",
    content: [],
  },
  {
    id: 31,
    documentId: "provisions",
    title: "Provisions",
    slug: "provisions",
    definition: "Les provisions sont des charges enregistrées pour couvrir un risque ou une dépense probable future. Elles servent à ne pas présenter une image trop optimiste des comptes.",
    content: [],
  },
  {
    id: 32,
    documentId: "dette-nette",
    title: "Dette nette",
    slug: "dette-nette",
    definition: "La dette nette correspond à la dette financière totale diminuée de la trésorerie disponible. Elle mesure l'endettement réel à supporter une fois le cash pris en compte.",
    content: [],
  },
  {
    id: 33,
    documentId: "leverage",
    title: "Leverage",
    slug: "leverage",
    definition: "Le leverage désigne le niveau d'endettement utilisé pour financer l'entreprise, souvent mesuré par un ratio de dette rapporté à l'EBITDA. Plus il est élevé, plus l'entreprise dépend de sa capacité à générer du cash.",
    content: [],
  },
  {
    id: 34,
    documentId: "covenants-bancaires",
    title: "Covenants bancaires",
    slug: "covenants-bancaires",
    definition: "Les covenants bancaires sont des engagements inscrits dans un contrat de financement qui imposent le respect de certains seuils financiers. Ils protègent les prêteurs en encadrant le risque de crédit.",
    content: [],
  },
  {
    id: 35,
    documentId: "impots-differes",
    title: "Impôts différés",
    slug: "impots-differes",
    definition: "Les impôts différés viennent des écarts temporaires entre la comptabilité et la fiscalité. Ils peuvent créer un actif ou un passif d'impôt différé, affectant l'analyse de la qualité du résultat.",
    content: [],
  },
];

const glossaryEn: StrapiGlossaryTerm[] = [
  {
    id: 1,
    documentId: "revenue",
    title: "Revenue",
    slug: "revenue",
    definition: "Revenue is the total amount of sales generated by a company over a given period. It shows the gross business activity before operating costs, taxes, or financing expenses are deducted.",
    content: [],
  },
  {
    id: 2,
    documentId: "gross-margin",
    title: "Gross Margin",
    slug: "gross-margin",
    definition: "Gross margin is what remains after subtracting the direct costs required to produce or deliver a product or service. It shows whether the offer creates enough value before overhead and support costs.",
    content: [],
  },
  {
    id: 3,
    documentId: "ebitda",
    title: "EBITDA",
    slug: "ebitda",
    definition: "EBITDA measures operating performance before interest, taxes, depreciation, and amortization. It isolates the earning power generated by the core business activity.",
    content: [],
  },
  {
    id: 4,
    documentId: "net-income",
    title: "Net Income",
    slug: "net-income",
    definition: "Net income is the final profit or loss after all expenses, including interest and taxes. It is the bottom-line result shown in the income statement.",
    content: [],
  },
  {
    id: 5,
    documentId: "cash-flow",
    title: "Cash Flow",
    slug: "cash-flow",
    definition: "Cash flow describes the money flowing in and out of a business. It shows whether the company is actually generating cash beyond accounting profit.",
    content: [],
  },
  {
    id: 6,
    documentId: "cash-position",
    title: "Cash Position",
    slug: "cash-position",
    definition: "Cash position is the money immediately available in bank accounts and cash equivalents. It determines the company's short-term ability to pay its obligations.",
    content: [],
  },
  {
    id: 7,
    documentId: "working-capital-requirement",
    title: "Working Capital Requirement",
    slug: "working-capital-requirement",
    definition: "Working capital requirement is the cash needed to finance the timing gap between customer receipts and supplier payments, including inventory.",
    content: [],
  },
  {
    id: 8,
    documentId: "working-capital",
    title: "Working Capital",
    slug: "working-capital",
    definition: "Working capital is the pool of stable resources available to finance operations. A common financial balance principle is that working capital should be sufficient to cover working capital requirement.",
    content: [],
  },
  {
    id: 9,
    documentId: "break-even-point",
    title: "Break-even Point",
    slug: "break-even-point",
    definition: "Break-even point is the level of revenue at which the company covers all its costs. Below that level, it loses money. Above it, it starts generating profit.",
    content: [],
  },
  {
    id: 10,
    documentId: "burn-rate",
    title: "Burn Rate",
    slug: "burn-rate",
    definition: "Burn rate measures how quickly a company is using up its cash reserves. It is widely used in startups and high-growth businesses.",
    content: [],
  },
  {
    id: 11,
    documentId: "runway",
    title: "Runway",
    slug: "runway",
    definition: "Runway is the number of months a company can continue operating with its current cash balance. It depends directly on burn rate.",
    content: [],
  },
  {
    id: 12,
    documentId: "budget",
    title: "Budget",
    slug: "budget",
    definition: "A budget is the forward plan of revenue, costs, and investments for a future period. It sets the expected path and gives teams a financial framework.",
    content: [],
  },
  {
    id: 13,
    documentId: "forecast",
    title: "Forecast",
    slug: "forecast",
    definition: "A forecast is an updated projection based on the latest actual data. It gives a more realistic view of where the year is heading.",
    content: [],
  },
  {
    id: 14,
    documentId: "income-statement",
    title: "Income Statement",
    slug: "income-statement",
    definition: "The income statement shows revenue and expenses over a given period to explain how profit or loss is formed. It tells the story of operating performance during the period.",
    content: [],
  },
  {
    id: 15,
    documentId: "balance-sheet",
    title: "Balance Sheet",
    slug: "balance-sheet",
    definition: "The balance sheet is a snapshot of the company's financial position at a specific date. It shows what the business owns and what it owes.",
    content: [],
  },
  {
    id: 16,
    documentId: "capital-expenditures",
    title: "Capital Expenditures",
    slug: "capital-expenditures",
    definition: "Capital expenditures are investments made to create value over several years. They include items such as equipment, major software, or production assets.",
    content: [],
  },
  {
    id: 17,
    documentId: "operating-expenses",
    title: "Operating Expenses",
    slug: "operating-expenses",
    definition: "Operating expenses are the recurring costs required to run the business. They include salaries, rent, subscriptions, and recurring marketing spend.",
    content: [],
  },
  {
    id: 18,
    documentId: "roi",
    title: "ROI",
    slug: "roi",
    definition: "Return on investment measures the gain generated compared with the cost of an investment. It helps determine whether money spent creates enough value.",
    content: [],
  },
  {
    id: 19,
    documentId: "debt",
    title: "Debt",
    slug: "debt",
    definition: "Debt is financing that the company must repay under agreed terms and timelines. It allows growth to be funded without giving up ownership.",
    content: [],
  },
  {
    id: 20,
    documentId: "equity",
    title: "Equity",
    slug: "equity",
    definition: "Equity is the capital contributed by shareholders or retained within the company. It forms the ownership base and strengthens the balance sheet.",
    content: [],
  },
  {
    id: 21,
    documentId: "dilution",
    title: "Dilution",
    slug: "dilution",
    definition: "Dilution is the reduction in an existing shareholder's ownership percentage after new shares are issued. It does not always mean lower absolute value, but it does mean a smaller share of the company.",
    content: [],
  },
  {
    id: 22,
    documentId: "valuation",
    title: "Valuation",
    slug: "valuation",
    definition: "Valuation is the estimated value of a company at a specific point in time. It is a key reference in fundraising, M&A, and strategic negotiations.",
    content: [],
  },
  {
    id: 23,
    documentId: "ltv",
    title: "Lifetime Value",
    slug: "ltv",
    definition: "Lifetime value measures the revenue or margin generated by a customer over the full relationship. It helps quantify the real long-term value of a client.",
    content: [],
  },
  {
    id: 24,
    documentId: "cac",
    title: "Customer Acquisition Cost",
    slug: "cac",
    definition: "Customer acquisition cost is the amount required to win a new customer. It usually includes marketing and sales expenses tied to acquisition.",
    content: [],
  },
  {
    id: 25,
    documentId: "free-cash-flow",
    title: "Free Cash Flow",
    slug: "free-cash-flow",
    definition: "Free cash flow is the cash truly available after operating needs and required investment spending. It shows how much cash the business can use freely.",
    content: [],
  },
  {
    id: 26,
    documentId: "net-asset-value",
    title: "Net Asset Value",
    slug: "net-asset-value",
    definition: "Net asset value is the value of assets minus liabilities. It is commonly used to assess holdings, funds, or companies where asset value is a major driver.",
    content: [],
  },
  {
    id: 27,
    documentId: "corporate-income-tax",
    title: "Corporate Income Tax",
    slug: "corporate-income-tax",
    definition: "Corporate income tax is generally an annual tax levied on profits earned by companies and certain legal entities.",
    content: [],
  },
  {
    id: 28,
    documentId: "taxable-income",
    title: "Taxable Income",
    slug: "taxable-income",
    definition: "Taxable income is the basis used to calculate corporate tax, derived from accounting profit after legal tax adjustments. It can differ significantly from reported profit.",
    content: [],
  },
  {
    id: 29,
    documentId: "vat",
    title: "VAT",
    slug: "vat",
    definition: "VAT is an indirect tax ultimately borne by the consumer and collected by businesses on behalf of the state. Companies charge VAT on sales and remit the balance after deducting VAT paid on purchases.",
    content: [],
  },
  {
    id: 30,
    documentId: "depreciation",
    title: "Depreciation",
    slug: "depreciation",
    definition: "Depreciation allocates the cost of an asset over its estimated useful life. It reflects the gradual consumption of the asset's value in accounting terms.",
    content: [],
  },
  {
    id: 31,
    documentId: "provisions",
    title: "Provisions",
    slug: "provisions",
    definition: "Provisions are expenses recorded to cover probable future risks or costs. They help avoid presenting an overly optimistic picture of the accounts.",
    content: [],
  },
  {
    id: 32,
    documentId: "net-debt",
    title: "Net Debt",
    slug: "net-debt",
    definition: "Net debt is total financial debt minus available cash. It measures the real indebtedness once liquidity is taken into account.",
    content: [],
  },
  {
    id: 33,
    documentId: "leverage",
    title: "Leverage",
    slug: "leverage",
    definition: "Leverage refers to the amount of debt used to finance a company, often measured through a debt-to-EBITDA style ratio. The higher it is, the more the business depends on cash generation to remain stable.",
    content: [],
  },
  {
    id: 34,
    documentId: "bank-covenants",
    title: "Bank Covenants",
    slug: "bank-covenants",
    definition: "Bank covenants are financial commitments written into loan agreements that require the borrower to stay within specific thresholds. They are designed to protect lenders by controlling credit risk.",
    content: [],
  },
  {
    id: 35,
    documentId: "deferred-taxes",
    title: "Deferred Taxes",
    slug: "deferred-taxes",
    definition: "Deferred taxes arise from temporary differences between accounting treatment and tax treatment. They may create a deferred tax asset or a deferred tax liability, affecting earnings quality analysis.",
    content: [],
  },
];

const glossaryEs: StrapiGlossaryTerm[] = [
  {
    id: 1,
    documentId: "ingresos",
    title: "Ingresos",
    slug: "ingresos",
    definition: "Los ingresos corresponden al total de ventas realizadas por una empresa durante un periodo. Miden la actividad comercial bruta, antes de restar costes y gastos.",
    content: [],
  },
  {
    id: 2,
    documentId: "margen-bruto",
    title: "Margen bruto",
    slug: "margen-bruto",
    definition: "El margen bruto es lo que queda después de restar los costes directamente vinculados a la venta o a la producción. Permite ver si la oferta genera valor antes de los gastos de estructura.",
    content: [],
  },
  {
    id: 3,
    documentId: "ebitda",
    title: "EBITDA",
    slug: "ebitda",
    definition: "El EBITDA mide el rendimiento operativo antes de intereses, impuestos y amortizaciones. Aísla la capacidad del negocio para generar resultado desde su actividad principal.",
    content: [],
  },
  {
    id: 4,
    documentId: "resultado-neto",
    title: "Resultado neto",
    slug: "resultado-neto",
    definition: "El resultado neto es el beneficio o la pérdida final después de todos los gastos, incluidos intereses e impuestos. Es la cifra final de la cuenta de resultados.",
    content: [],
  },
  {
    id: 5,
    documentId: "flujo-caja",
    title: "Flujo de caja",
    slug: "flujo-de-caja",
    definition: "El flujo de caja describe el dinero que entra y sale de la empresa. Muestra si el negocio genera caja real, más allá del resultado contable.",
    content: [],
  },
  {
    id: 6,
    documentId: "tesoreria",
    title: "Tesorería",
    slug: "tesoreria",
    definition: "La tesorería es el dinero disponible de forma inmediata en cuentas bancarias y equivalentes. Permite pagar gastos corrientes sin esperar nuevos cobros.",
    content: [],
  },
  {
    id: 7,
    documentId: "necesidad-capital-circulante",
    title: "Necesidad de capital circulante",
    slug: "necesidad-de-capital-circulante",
    definition: "La necesidad de capital circulante es el dinero necesario para financiar el desfase entre cobros y pagos, incluyendo existencias. Aumenta cuando la empresa debe adelantar caja antes de cobrar.",
    content: [],
  },
  {
    id: 8,
    documentId: "fondo-maniobra",
    title: "Fondo de maniobra",
    slug: "fondo-de-maniobra",
    definition: "El fondo de maniobra corresponde a los recursos estables disponibles para financiar la actividad. El equilibrio financiero clásico consiste en cubrir la necesidad de capital circulante con un fondo suficiente.",
    content: [],
  },
  {
    id: 9,
    documentId: "punto-equilibrio",
    title: "Punto de equilibrio",
    slug: "punto-de-equilibrio",
    definition: "El punto de equilibrio es el nivel de ingresos a partir del cual la empresa cubre todos sus costes. Por debajo pierde dinero. Por encima empieza a generar beneficio.",
    content: [],
  },
  {
    id: 10,
    documentId: "tasa-consumo-caja",
    title: "Tasa de consumo de caja",
    slug: "tasa-de-consumo-de-caja",
    definition: "La tasa de consumo de caja mide la velocidad a la que una empresa utiliza su tesorería. Es muy usada en startups y negocios en fase de inversión.",
    content: [],
  },
  {
    id: 11,
    documentId: "pista-financiera",
    title: "Pista financiera",
    slug: "pista-financiera",
    definition: "La pista financiera es el número de meses que la empresa puede seguir operando con la caja disponible. Depende directamente del burn rate.",
    content: [],
  },
  {
    id: 12,
    documentId: "presupuesto",
    title: "Presupuesto",
    slug: "presupuesto",
    definition: "El presupuesto es la proyección de ingresos, costes e inversiones para un periodo futuro. Marca una trayectoria esperada y un marco de decisión.",
    content: [],
  },
  {
    id: 13,
    documentId: "prevision-actualizada",
    title: "Previsión actualizada",
    slug: "prevision-actualizada",
    definition: "La previsión actualizada es una revisión del presupuesto basada en los datos reales más recientes. Ofrece una visión más realista del cierre del periodo.",
    content: [],
  },
  {
    id: 14,
    documentId: "cuenta-resultados",
    title: "Cuenta de resultados",
    slug: "cuenta-de-resultados",
    definition: "La cuenta de resultados presenta ingresos y gastos de un periodo para explicar cómo se forma el beneficio o la pérdida. Resume el rendimiento económico del ejercicio.",
    content: [],
  },
  {
    id: 15,
    documentId: "balance",
    title: "Balance",
    slug: "balance",
    definition: "El balance es una fotografía de la situación patrimonial de la empresa en una fecha concreta. Muestra lo que posee y lo que debe.",
    content: [],
  },
  {
    id: 16,
    documentId: "inversiones-capital",
    title: "Inversiones de capital",
    slug: "inversiones-de-capital",
    definition: "Las inversiones de capital son gastos destinados a crear valor durante varios años. Incluyen maquinaria, software estructural o equipamientos relevantes.",
    content: [],
  },
  {
    id: 17,
    documentId: "gastos-operativos",
    title: "Gastos operativos",
    slug: "gastos-operativos",
    definition: "Los gastos operativos son los costes recurrentes necesarios para hacer funcionar la empresa. Incluyen salarios, alquileres, suscripciones y marketing recurrente.",
    content: [],
  },
  {
    id: 18,
    documentId: "roi",
    title: "Retorno sobre la inversión",
    slug: "roi",
    definition: "El retorno sobre la inversión mide el beneficio obtenido frente al coste de una inversión. Permite saber si el dinero invertido genera suficiente valor.",
    content: [],
  },
  {
    id: 19,
    documentId: "deuda",
    title: "Deuda",
    slug: "deuda",
    definition: "La deuda es una financiación que la empresa debe devolver según condiciones y plazos pactados. Permite crecer sin ceder capital.",
    content: [],
  },
  {
    id: 20,
    documentId: "capital-propio",
    title: "Capital propio",
    slug: "capital-propio",
    definition: "El capital propio representa los fondos aportados o retenidos por los accionistas en la empresa. Es la base de la propiedad y de la solidez financiera.",
    content: [],
  },
  {
    id: 21,
    documentId: "dilucion",
    title: "Dilución",
    slug: "dilucion",
    definition: "La dilución es la reducción del porcentaje de participación de un accionista tras emitir nuevas acciones. No implica necesariamente perder valor absoluto, pero sí tener una porción menor de la empresa.",
    content: [],
  },
  {
    id: 22,
    documentId: "valoracion",
    title: "Valoración",
    slug: "valoracion",
    definition: "La valoración es la estimación del valor de una empresa en un momento concreto. Sirve como base en rondas de financiación, ventas o negociaciones estratégicas.",
    content: [],
  },
  {
    id: 23,
    documentId: "valor-vida-cliente",
    title: "Valor de vida del cliente",
    slug: "valor-de-vida-del-cliente",
    definition: "El valor de vida del cliente mide los ingresos o margen generados por un cliente durante toda la relación. Ayuda a entender cuánto vale realmente un cliente a largo plazo.",
    content: [],
  },
  {
    id: 24,
    documentId: "coste-adquisicion-cliente",
    title: "Coste de adquisición de cliente",
    slug: "coste-de-adquisicion-de-cliente",
    definition: "El coste de adquisición de cliente es el importe necesario para conseguir un nuevo cliente. Suele incluir gastos de marketing y ventas vinculados a captación.",
    content: [],
  },
  {
    id: 25,
    documentId: "flujo-caja-libre",
    title: "Flujo de caja libre",
    slug: "flujo-de-caja-libre",
    definition: "El flujo de caja libre es la caja realmente disponible después de cubrir la operativa y las inversiones necesarias. Muestra cuánto efectivo puede usar libremente la empresa.",
    content: [],
  },
  {
    id: 26,
    documentId: "valor-neto-activos",
    title: "Valor neto de los activos",
    slug: "valor-neto-de-los-activos",
    definition: "El valor neto de los activos corresponde al valor de los activos menos las deudas. Se utiliza mucho para analizar holdings, fondos o empresas donde el peso de los activos es relevante.",
    content: [],
  },
  {
    id: 27,
    documentId: "impuesto-sociedades",
    title: "Impuesto sobre sociedades",
    slug: "impuesto-sobre-sociedades",
    definition: "El impuesto sobre sociedades es, en general, un impuesto anual que grava los beneficios obtenidos por sociedades y determinadas personas jurídicas.",
    content: [],
  },
  {
    id: 28,
    documentId: "resultado-fiscal",
    title: "Resultado fiscal",
    slug: "resultado-fiscal",
    definition: "El resultado fiscal es la base utilizada para calcular el impuesto, partiendo del resultado contable y aplicando ajustes legales. Por eso puede diferir del beneficio mostrado en cuentas.",
    content: [],
  },
  {
    id: 29,
    documentId: "iva",
    title: "IVA",
    slug: "iva",
    definition: "El IVA es un impuesto indirecto soportado por el consumidor y recaudado por la empresa en nombre del Estado. La empresa repercute IVA en sus ventas y entrega la diferencia tras deducir el IVA soportado.",
    content: [],
  },
  {
    id: 30,
    documentId: "amortizacion",
    title: "Amortización",
    slug: "amortizacion",
    definition: "La amortización distribuye el coste de un activo a lo largo de su vida útil estimada. Refleja contablemente el consumo progresivo del valor de esa inversión.",
    content: [],
  },
  {
    id: 31,
    documentId: "provisiones",
    title: "Provisiones",
    slug: "provisiones",
    definition: "Las provisiones son gastos reconocidos para cubrir un riesgo o un coste futuro probable. Evitan presentar unas cuentas demasiado optimistas.",
    content: [],
  },
  {
    id: 32,
    documentId: "deuda-neta",
    title: "Deuda neta",
    slug: "deuda-neta",
    definition: "La deuda neta es la deuda financiera total menos la tesorería disponible. Mide el endeudamiento real una vez considerada la caja.",
    content: [],
  },
  {
    id: 33,
    documentId: "apalancamiento",
    title: "Apalancamiento",
    slug: "apalancamiento",
    definition: "El apalancamiento describe el nivel de deuda utilizado para financiar la empresa, a menudo medido con un ratio de deuda sobre EBITDA. Cuanto más alto es, más depende la empresa de generar caja.",
    content: [],
  },
  {
    id: 34,
    documentId: "covenants-bancarios",
    title: "Covenants bancarios",
    slug: "covenants-bancarios",
    definition: "Los covenants bancarios son compromisos financieros incluidos en un contrato de financiación que obligan a respetar determinados umbrales. Protegen al prestamista al limitar el riesgo de crédito.",
    content: [],
  },
  {
    id: 35,
    documentId: "impuestos-diferidos",
    title: "Impuestos diferidos",
    slug: "impuestos-diferidos",
    definition: "Los impuestos diferidos nacen de diferencias temporarias entre el tratamiento contable y el fiscal. Pueden generar un activo por impuesto diferido o un pasivo por impuesto diferido, afectando el análisis de calidad del resultado.",
    content: [],
  },
];

export function getFallbackGlossaryTerms(locale: "fr" | "en" | "es"): StrapiGlossaryTerm[] {
  const glossaries: Record<"fr" | "en" | "es", StrapiGlossaryTerm[]> = {
    fr: glossaryFr,
    en: glossaryEn,
    es: glossaryEs,
  };
  return glossaries[locale] || [];
}
